Tweaks weed node damage threshold
RMC-14/RMC-14 pull request #2560
Opened 2024-06-22 22:42 UTC by vero5123

## About the PR
closes #2375 
## Why / Balance
requested tweak, for reference it takes two hits with a bayonet knife to destroy weeds now.

## Technical details
increased the damage from 5 to 30 for weed nodes. Takes 2 hits with a standard bayonet knife and more with entities that have lower damage output.

## Media
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
:cl:
- tweak: increased the required damage threshold to destroy weed nodes

2024-06-23 05:06 UTC, DrSmugleaf commented
I need to ask Skarlet about this but from testing in CMSS13 the weed nodes do take one hit to destroy with a bayonet for me, not two

2024-06-25 03:39 UTC, QuietlyWhisper requested changes
smug says it should be 33

2024-06-25 03:39 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Structures/Xeno/xeno_weeds.yml
> +        damage: 30
```suggestion
        damage: 33
```

2024-06-25 03:39 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Structures/Xeno/xeno_weeds.yml
> +        damage: 30
```suggestion
        damage: 33
```

2024-06-25 03:40 UTC, QuietlyWhisper approved these changes
thanks

2024-06-25 03:40 UTC, merged