Ports Shiva Walls and Windows
RMC-14/RMC-14 pull request #2614
Opened 2024-06-24 21:36 UTC by noctyrnal

## About the PR

Ports walls and windows for Shiva's Snowball

## Why / Balance

Needed for Shiva's Snowball

## Technical details

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/RMC-14/RMC-14/assets/99278536/b06d98eb-5d6f-4fde-9122-68c17451b89a)

## Breaking changes

**Changelog**

none needed i think

2024-06-24 21:55 UTC, noctyrnal commented
Marking as draft so I can include more in the PR

2024-06-28 00:51 UTC, QuietlyWhisper requested changes
Early but not entirely complete draft review, but make sure all new content IDs are `RMC` and not `CM`,  also noticed you had an "invincible" entity that had damageable component

2024-06-28 00:51 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Structures/Walls/walls.yml
> +        acts: [ "Destruction" ]
`CMWallShivaInvincibleFab`
```suggestion
```

2024-06-30 11:43 UTC, noctyrnal commented
Marking as ready for review as I need a much larger list for a second PR for all the shiva content im missing, most of which is just items and furniture

2024-07-03 11:26 UTC, QuietlyWhisper approved these changes
Thanks

2024-07-03 11:26 UTC, merged