Tweak chemical dispenser fill and nuke non-cm13 chemicals
RMC-14/RMC-14 pull request #2625
Opened 2024-06-25 13:22 UTC by UbaserB

## About the PR

Tweaks the chemical dispenser's fill by nuking iodine, alongside getting rid of zinc as a chemical. Referencing https://cm-ss13.com/wiki/Chemistry#Chemicals.

Resolves #2438.

2024-06-25 13:29 UTC, Tunguso4ka commented on Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml
thats upstream chem dispenser.

2024-06-25 13:55 UTC, UbaserB commented on Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml
fixed

2024-06-25 14:07 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Catalog/ReagentDispensers/chemical.yml
Im already added both ChemDispenser Standard and Empty Inventories in `Resources/Prototypes/_RMC14/Entities/Structures/Machines/Science/Dispensers/chem.yml`

2024-06-25 14:40 UTC, UbaserB commented on Resources/Prototypes/_RMC14/Catalog/ReagentDispensers/chemical.yml
fixed

2024-07-01 12:43 UTC, Tunguso4ka requested changes
colors and migration.yml

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Entities/Objects/Specific/chemical-containers.yml
> +  parent: BaseItem
you can use CMBeakerBase as parent here. Its located in `Resources/Prototypes/_RMC14/Entities/Objects/Medical/beaker.yml`
would be good if you moved your .yml file there too.

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Entities/Structures/Machines/Science/Dispensers/chem.yml
> +  id: RMCDispenserChem
add that to `migration.yml`

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Entities/Structures/Machines/Science/Dispensers/chem.yml
> +  id: RMCDispenserChemEmpty
`migration.yml`

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  id: RMCAluminium
idk why, but in cm-ss13 it called "Aluminum"
```
/datum/reagent/aluminum
name = "Aluminum"
```
from 'code/modules/reagents/chemistry_reagents/other.dm' line `461`

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#848789"
`#A8A8A8`

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#22282b"
```suggestion
  color: "#1C1300"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#a2ff00"
```suggestion
  color: "#808080"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#b05b3c"
```suggestion
  color: "#6E3B08"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#ba85cc"
```suggestion
  color: "#808080"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#cccccc"
```suggestion
  color: "#808080"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#434b4d"
```suggestion
  color: "#C8A5DC"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#d6c0a7"
```suggestion
  color: "#808080"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#929296"
```suggestion
  color: "#484848"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#c6c8cc"
```suggestion
  color: "#A0A0A0"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#f5da9a"
```suggestion
  color: "#832828"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#00ff04"
```suggestion
  color: "#C7C7C7"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#364266"
```suggestion
  color: "#A8A8A8"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#fff385"
```suggestion
  color: "#BF8C00"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#a7b3d6"
```suggestion
  color: "#808080"
```

2024-07-01 12:43 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  color: "#8fa191"
```suggestion
  color: "#B8B8C0"
```

2024-07-01 12:47 UTC, Tunguso4ka requested changes

2024-07-01 12:47 UTC, Tunguso4ka commented on Resources/Locale/_RMC14/reagents/meta/elements.ftl
> +reagent-desc-sulphuric-rmc-acid = A corrosive chemical. Keep away from your face.
```suggestion
reagent-name-rmc-sulphuric-acid = sulphuric acid
reagent-desc-rmc-sulphuric-acid = A corrosive chemical. Keep away from your face.
```

2024-07-01 12:47 UTC, Tunguso4ka commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +  desc: reagent-desc-sulphuric-rmc-acid
```suggestion
  name: reagent-name-rmc-sulphuric-acid
  group: Toxins
  desc: reagent-desc-rmc-sulphuric-acid
```

2024-07-01 12:49 UTC, Tunguso4ka commented on Resources/Locale/_RMC14/reagents/meta/elements.ftl
> +reagent-desc-sulphuric-rmc-acid = A corrosive chemical. Keep away from your face.
WAIT, why is that file in `Resources/Locale/_RMC14/` ??? move it to `Resources/Locale/en-US/_RMC14`

2024-07-01 13:17 UTC, Tunguso4ka approved these changes
good work!

2024-07-01 14:51 UTC, UbaserB commented
It's done now, I dont want to increase the scope too far.

2024-07-04 10:13 UTC, QuietlyWhisper requested changes
We'll probably need to redo the chem machine later but this is mostly reagents for recipes anyway

2024-07-04 10:13 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Reagents/elements.yml
> +- type: reagent
```suggestion
# todo rmc14 these should have their effects checked for 13 values
- type: reagent
```

2024-07-04 10:15 UTC, QuietlyWhisper approved these changes

2024-07-04 10:31 UTC, merged