Trijent tiles port 1
RMC-14/RMC-14 pull request #2626
Opened 2024-06-25 16:30 UTC by UnicornOnLSD

## About the PR

desert tiles

it's bugged and don't show up yet, draft
## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-06-28 01:36 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Tiles/planet/red_desert/desert_transition_edge8.png
Empty sprite?

2024-06-28 01:41 UTC, QuietlyWhisper requested changes

2024-06-28 01:41 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Tiles/trijent.yml
New content IDs should be `RMC` and not `CM`

2024-06-28 01:41 UTC, QuietlyWhisper commented on Resources/Locale/en-US/_RMC14/tiles/tiles.ftl
> +tiles-cm-red-desert = red desert tile
`tiles-rmc-red-desert = red desert tile`
Make sure to replace in .YML file as well

2024-06-28 13:52 UTC, UnicornOnLSD commented on Resources/Textures/_RMC14/Tiles/planet/red_desert/desert_transition_edge8.png
mbad, this one slipped under the radar, will nuke it

2024-07-03 11:07 UTC, DrSmugleaf approved these changes

2024-07-03 11:07 UTC, DrSmugleaf commented
Thanks for the PR!

2024-07-03 11:07 UTC, merged