Walls and windows for Fiorina.
RMC-14/RMC-14 pull request #2632
Opened 2024-06-26 01:49 UTC by Cu1r

## About the PR
Added 4 window types and 4 wall types for Fiorina Science Annex.

## Why / Balance
Fiorina need walls to keep the marines from discovering breathing is optional now and barotrauma doesn't exist.

## Media
![walls](https://github.com/RMC-14/RMC-14/assets/123379145/3367ed63-361a-4848-8312-8faa827eb375)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-06-26 04:24 UTC, QuietlyWhisper requested changes
I don't think the window sprites are correct here, they shouldn't be individual sprites

2024-06-26 04:24 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Structures/Walls/bone_resin.rsi/bone_resin.png
Don't think you need this image if I'm not mistaken

2024-06-26 04:24 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Structures/Walls/prison_rwall.rsi/hwall.png
Don't think you need this image if I'm not mistaken

2024-06-26 04:24 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Structures/Walls/prison_rwall.rsi/rwall.png
Don't think you need this image if I'm not mistaken

2024-06-26 04:24 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Structures/Walls/prison_wall.rsi/metal.png
Don't think you need this image if I'm not mistaken

2024-06-26 04:24 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Structures/Windows/windows.yml
Can you add todo rmc14 to these comments

2024-07-03 11:53 UTC, DrSmugleaf submitted a review, later dismissed
Thanks for the PR! We can fix the smoothing later

2024-07-03 12:07 UTC, DrSmugleaf approved these changes

2024-07-03 12:07 UTC, merged