Add a phoron crate, a new requisitions tab and make phoron obtainable.
RMC-14/RMC-14 pull request #2663
Opened 2024-06-28 16:12 UTC by Zarq0

## About the PR

Added a phoron crate, a new requisitions tab, Research and made phoron obtainable through requisitions.

## Why / Balance

The phoron crate was ported so the items added in the future to the research tab for requisitions has their own crate to use.
Made phoron obtainable through requisitions so the bars can be ordered and grinded for the Phoron reagent, it is needed to make some medicinal reagents.

## Media

https://github.com/RMC-14/RMC-14/assets/75623951/1aac0567-2faa-4f75-a67f-d7ae3c020f56

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Ported the phoron crate.
- add: Added a new requisition tab, Research.
- tweak: Made phoron obtainable through requisitions.

2024-06-29 02:16 UTC, QuietlyWhisper requested changes
TLDR
- use `CMCrateSecure` as a parent for the empty crate
- drop the new rsi and sprites
- make a 30 stack of phoron for the crate

2024-06-29 02:16 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Structures/Storage/crates.yml
> +
```suggestion
  parent: CMCrateSecure
  id: RMCCratePhoron
  name: phoron crate
  description: A phoron crate.
  components:
  - type: AccessReader
    access: [["CMAccessResearch"],["CMAccessEngineering"]]

```
Drop the new RSI, 13 uses the secure crate, and you'd need access locks sprites, and a place to put the req paperwork, so it's overall better to use `CMCrateSecure` as a parent anyways so you don't need to create anything new.

Make sure to test these changes after though

2024-06-29 10:57 UTC, Zarq0 commented
Done,  made the changes requested, tested and they seem to work for me.

2024-06-29 11:16 UTC, Zarq0 commented
https://github.com/RMC-14/RMC-14/assets/75623951/fa8a6781-8488-4a53-bde9-8b6dacf938df

2024-06-30 09:34 UTC, QuietlyWhisper approved these changes
Seems to be fine thanks!

2024-06-30 09:35 UTC, merged