Adds Wehny
RMC-14/RMC-14 pull request #2668
Opened 2024-06-30 06:08 UTC by Kadeo64

## About the PR

Adds Wehny, a horrible, horrible abomination of weh and rouny. It's an admin only spawn.
## Why / Balance
Admeme xeno with 4000 health (3900 till crit) and 50 blunt damage at 2 swing speed. It's also double the default runner's speed. good luck.
## Technical details
parented from runner.yml with values changed
## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![god](https://github.com/RMC-14/RMC-14/assets/108914677/d7ad37d9-622a-4a2b-84fa-edfd1470e4bc)

2024-06-30 10:14 UTC, snebl commented
He needs to be able to make a weh sound imo.

2024-06-30 18:23 UTC, USMP-lancer commented
while your at it, add a glass rouny with 90% reflect chance but has literally 1 health

2024-06-30 18:26 UTC, a-person5660 commented
> while your at it, add a glass rouny with 90% reflect chance but has literally 1 health

it would die in 10 shots on average, you would want much more for it to survive anything.

2024-07-03 12:11 UTC, QuietlyWhisper requested changes

2024-07-03 12:11 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Mobs/Xeno/wehny.yml
> +    - CMXenoWehny
```suggestion
  - type: XenoEvolution
    max: 300
    evolvesTo: [ ]
```

2024-07-03 12:16 UTC, QuietlyWhisper commented
You should add rouny too :)

2024-07-03 23:33 UTC, Kadeo64 commented
> You should add rouny too :)

i'll do rouny after this probably

2024-07-04 08:08 UTC, QuietlyWhisper approved these changes
I'm sure it's fine

2024-07-04 08:08 UTC, merged