De-red-ify more crosses
RMC-14/RMC-14 pull request #2764
Opened 2024-07-02 16:45 UTC by MACMAN2003

## About the PR

un-redded even more red crosses
## Why / Balance

i missed a few
## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-07-03 12:05 UTC, QuietlyWhisper approved these changes
thanks

2024-07-03 12:06 UTC, QuietlyWhisper requested changes

2024-07-03 12:06 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Interface/health_hud.rsi/hudhealthy.png
I just remembered you'll need to fix this image because it got scaled down

2024-07-03 23:03 UTC, MACMAN2003 commented
i think it's ready??? (git is evil i hate it)

2024-07-04 08:12 UTC, QuietlyWhisper approved these changes
Thanks!

2024-07-04 08:12 UTC, merged