Large dump of various things on my mapping wishlist
RMC-14/RMC-14 pull request #2853
Opened 2024-07-06 12:59 UTC by Cu1r

## About the PR
Added various things I wanted to map that were missing from the catalog:

Two bed variants
Prison-type table
Constructible RMC grille with broken variant
Monorail track pieces
U-shaped platform piece
Constructible RMC wooden barricade
RMC wood plank material and item stacks to build the barricade with
(moved material types and stack types out of the "other" mats item section and into the places they actually go because clutter. It's a very large mess and out of all the things that need to be fixed in there I can at least put stuff where it goes. Secret maintainer cabal don't murder me pls)
RMC inflatable walls and doors with broken variants
Folded inflatable structure item stacks
25 unit filled sandbag stack and 30 unit metal sheet stack because grrr mapping

 Might have gotten a bit carried away, I hope it's not to much for one PR.

## Why / Balance
All of these things are on the map I'm porting and I think they all add something to it.

## Media
![wishlist](https://github.com/RMC-14/RMC-14/assets/123379145/63a12d2f-c6e6-42c7-a5f8-23a323b03574)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

2024-07-07 10:56 UTC, QuietlyWhisper requested changes

2024-07-07 10:56 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Recipes/Construction/Graphs/structures/grille.yml
> +        amount: 2
```suggestion
        amount: 4
```

2024-07-07 10:56 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Recipes/Construction/Graphs/structures/grille.yml
> +        amount: 2
```suggestion
        amount: 1
```

2024-07-07 10:56 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Recipes/Construction/Graphs/structures/barricade_wood.yml
> +        doAfter: 5
It doesn't seem like you can deconstruct these in 13 so remove this unless you know otherwise

2024-07-08 11:16 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-07-08 11:16 UTC, merged