Hivelord replace door
RMC-14/RMC-14 pull request #2875
Opened 2024-07-07 12:57 UTC by ShadowCommander

## About the PR

Added the ability for Hivelords to upgrade resin walls, doors, and membrane to their thick versions without having to destroy the previous structure.

## Why / Balance

Faster hive reinforcement and porting features from CM13.

## Technical details

Added a new action type EntityWorldTargetActionComponent that provides both an EntityUid and an EntityCoordinates.

Changed XenoSecreteStructureActionEvent to use EntityWorldTargetActionComponent.

Changed 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Thickening walls, doors, and membrane:

https://github.com/RMC-14/RMC-14/assets/10494922/9526c807-72e2-4a31-874e-a6b0ea594473

Also works on walls with nests:

https://github.com/RMC-14/RMC-14/assets/10494922/b3a3dcf4-ce1d-4707-b2d7-1d24f57d03ca

## Breaking changes

**Changelog**

:cl:
- add: Hivelords can now use secrete resin to thicken the normal resin walls, doors, and membrane.

2024-07-07 15:38 UTC, Kadeo64 commented
DRONE WALLS ARE BETTER THAN NO WALLS!!

2024-07-08 03:54 UTC, DrSmugleaf requested changes
See review comments, if you were planning to upstream this though then you can ignore them

2024-07-08 03:54 UTC, DrSmugleaf commented on Content.Client/Actions/ActionsSystem.cs
> +        }
This and any other code changes that can be moved should go into their own RMC-specific code files.

2024-07-08 03:54 UTC, DrSmugleaf commented on Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
> +    }
This can be moved out too and be replaced with a method call to the rmc system where it is used.

2024-07-08 03:54 UTC, DrSmugleaf commented on Content.Server/Actions/ActionOnInteractSystem.cs
> +                return;
Same here

2024-07-08 03:54 UTC, DrSmugleaf commented on Content.Shared/Actions/ActionEvents.cs
> +}
And here

2024-07-08 03:54 UTC, DrSmugleaf commented on Content.Shared/Actions/EntityWorldTargetActionComponent.cs
> +public sealed partial class EntityWorldTargetActionComponent : BaseTargetActionComponent
Same here, these should be under _RMC14

2024-07-08 03:54 UTC, DrSmugleaf commented on Content.Shared/Actions/Events/ValidateActionEntityWorldTargetEvent.cs
> +public record struct ValidateActionEntityWorldTargetEvent(
Same here, this should be under _RMC14

2024-07-08 03:54 UTC, DrSmugleaf commented on Content.Shared/Actions/SharedActionsSystem.cs
> +        SubscribeLocalEvent<EntityWorldTargetActionComponent, MapInitEvent>(OnActionMapInit);
Same for these subscriptions

2024-07-08 03:57 UTC, ShadowCommander commented
Going to test it here and then upstream it yeah.

2024-08-08 17:47 UTC, deltanedas commented
with action refactor upstream the entity world target goodcode will be folded into having both Entity and World target action components so this would look something like

```yml
- type: Action
  # icon and stuff
- type: TargetAction
  # range
- type: EntityTargetAction
  whitelist:
    # drone walls/doors
  targetSelf: false
- type: WorldTargetAction
  event: !type:XenoBuildThingEvent
```

keep this in mind :trollface:

2024-09-06 00:00 UTC, TheDoctor1977 commented
Is this still being worked on? Waiting for something upstream?

2024-09-06 00:02 UTC, Dutch-VanDerLinde commented
> Is this still being worked on? Waiting for something upstream?

already got merged upstream

2024-09-07 05:16 UTC, ShadowCommander commented
Was waiting for upstream merges into RMC, but other than that I've just been working on non-SS14 projects for a bit. I'll get to this soon.

2024-11-18 07:06 UTC, closed without merging

2024-11-18 07:06 UTC, Vermidia commented
This was already implemented I think so closing this for now.