RMC admin PDA that scans
RMC-14/RMC-14 pull request #3136
Opened 2024-07-18 19:14 UTC by TsjipTsjip

## About the PR

Adds an RMC admin PDA and adds it to default admin loadout. It scans with a RMC health analyzer UI!

## Why / Balance

Admins need to be able to tell time.

## Technical details

I am painfully aware of the utter madness that is adding the health scanner UI to all PDA's, but it's how upstream does it so who am I to argue?

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

n/a

## Breaking changes

n/a

**Changelog**

None.

2024-07-19 13:00 UTC, QuietlyWhisper commented
- #3124 
maybe mix these two into one pr

2024-07-20 07:19 UTC, TsjipTsjip commented
@QuietlyWhisper This PR now supercedes #3124 .

2024-07-20 07:30 UTC, QuietlyWhisper requested changes

2024-07-20 07:30 UTC, QuietlyWhisper commented on Resources/Prototypes/Entities/Objects/Devices/pda.yml
> +        type: HealthScannerBoundUserInterface
if you move this entire component onto the RMC pda you dont have to touch this file

2024-07-20 07:30 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Roles/Jobs/Fun/rmc_admin_ghost.yml
>      - RMCAdminAccessConfigurator
put the base default analyzer here as well for deeper damage debugging as well
Not sure if this is the right id
```suggestion
    - RMCAdminAccessConfigurator
    - HealthAnalyzer
```

2024-07-20 07:30 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Roles/Jobs/Fun/rmc_admin_ghost.yml
> +  - type: Marine
smug said to remove this in the end for potential issues, we'll have a proper component for the purpose of this later
```suggestion
```

2024-07-20 08:17 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Roles/Jobs/Fun/rmc_admin_ghost.yml
> +    - HandheldHealthAnalyzer
```suggestion
    - HandheldHealthAnalyzerUnpowered
```

2024-07-20 08:19 UTC, QuietlyWhisper approved these changes
thanks

2024-07-20 09:44 UTC, merged