Add xenos un nest host action
RMC-14/RMC-14 pull request #3145
Opened 2024-07-19 04:22 UTC by Derrek-Larson

## About the PR

Added ability for Xenos to unnest marines!
## Why / Balance

Dead marines clog up walls. Xenos should logically be able to remove marines from nest. Existing feature in CM SS13.
## Technical details

Xenos can now ActivateInWorldEvent on a nested marine to begin unnesting them. After 8 seconds, the marine will be freed from the wall using existing DetachNest behavior.
Xenos will be warned while unnesting a non-crit non-dead marine and have plenty of time to cancel the action. If marine is crit or dead, the xenos will receive a different appropriate popup.
## Media

https://github.com/user-attachments/assets/0dd5d320-5285-4653-9637-d748b478d962

- [ x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

+ namespace Content.Shared._RMC14.Xenonids.Construction.Nest XenoUnNestDoAfterEvent.cs
++ public sealed partial class XenoUnNestDoAfterEvent : SimpleDoAfterEvent
+ xeno-nest.ftl new localizable strings associated with UnNesting action
+ XenoNestSystem.cs 2 new event listeners, associated functions
++ <XenoNestableComponent, ActivateInWorldEvent>
++ <XenoNestedComponent, XenoUnNestDoAfterEvent>
++ functions to facilitate unnesting a marine from a nest, return out if not used by xenos/on nested entity
**Changelog**

- add: Xenos can now remove bodies from nests, be careful if they're still kicking!

2024-07-19 04:28 UTC, Derrek-Larson commented
One thing I wasn't sure about was which interaction to use, and whether that action should target the marine or wall. Let me know if the action used isn't the appropriate one. I can also definitely add this behavior to using the action on the nest wall with nested entity in it, just didn't want to put in extra time until I'm sure the underlying logic and action choice is correct.

2024-07-20 11:03 UTC, DrSmugleaf requested changes
This needs to be instant with a popup like 13
Also in the future needs to be toggleable by the Queen, but you don't need to do that in this PR

https://github.com/user-attachments/assets/fb47ebdb-18fe-4b35-923a-66beab00ddfd

2024-07-20 18:56 UTC, Derrek-Larson commented
> This needs to be instant with a popup like 13 Also in the future needs to be toggleable by the Queen, but you don't need to do that in this PR
> 
>  dreamseeker_UJu00YTivx.mp4

Understood, I'll work on this today. Will need to learn how to do pop-ups, hopefully done by monday at latest.

2024-07-21 14:42 UTC, Dutch-VanDerLinde commented
> > This needs to be instant with a popup like 13 Also in the future needs to be toggleable by the Queen, but you don't need to do that in this PR
> > dreamseeker_UJu00YTivx.mp4
> 
> Understood, I'll work on this today. Will need to learn how to do pop-ups, hopefully done by monday at latest. I'll also work in activating it while mousing over the associated nest wall from the correct direction while I'm making changes.

You can use [**QuickDialogSystem**](https://github.com/RMC-14/RMC-14/blob/a386116a1ecbb87f3571e1688c573ba322a9279f/Content.Client/Administration/QuickDialogSystem.cs#L9) for this

![image](https://github.com/user-attachments/assets/6ed6df01-04d1-4855-bfda-4295c4ccec23)

2024-07-21 14:46 UTC, Dutch-VanDerLinde commented
> > This needs to be instant with a popup like 13 Also in the future needs to be toggleable by the Queen, but you don't need to do that in this PR
> > dreamseeker_UJu00YTivx.mp4
> 
> Understood, I'll work on this today. Will need to learn how to do pop-ups, hopefully done by monday at latest. I'll also work in activating it while mousing over the associated nest wall from the correct direction while I'm making changes.

this [pull request](https://github.com/space-wizards/space-station-14/pull/23315) can help you learn how to make popups

![image](https://github.com/user-attachments/assets/c1c718b1-4aed-4f86-8b8e-71ccec9c1802)

2024-08-01 00:02 UTC, Derrek-Larson commented
Sorry for the delay, life and work nuked me this week. i'll be back to working on this a bit tomorrow, with the helpful tips I expect to finish it then.

2024-08-09 19:01 UTC, Derrek-Larson commented
Good news, I have produced a crash which means I'm getting somewhere.
Bad news, I don't understand the reason for the crash.
Exception printout:
Unhandled exception. System.Exception: No precompiled XAML found for Content.Client._RMC14.Xenonids.Construction.Nest.XenoRemoveNestedWindow, make sure to specify Class or name your class the same as your .xaml
 As far as I can tell, My class is named XenoRemoveNestedWindow and has the namespace Content.Client._RMC14.Xenonids.Construction.Nest;
 So I'm a bit confused why this exception is occurring.

2024-08-09 20:59 UTC, blueDev2 commented
So with regard to the Content.Client.csproj file, I don't think that should be changed and probably should be reverted.

This is a bit of a shot in the dark, but how about creating a new folder in Content.Client/_RMC14/Xenoids/Construction called Nest and putting all the un-nesting client files into it so that the namespace follows how the files are actually organized.

2024-08-20 04:05 UTC, Derrek-Larson commented
Works now.

2024-08-22 03:23 UTC, Derrek-Larson reviewed
wow how did I mess this up again lol jfc will fix.

2024-09-11 19:38 UTC, Dutch-VanDerLinde commented
merg when!? !?!?!

2024-09-12 13:11 UTC, Derrek-Larson commented
> merg when!? !?!?!

hopefully soon i don't know how many catchup merges I got left in me. it works.

2024-09-12 14:18 UTC, DrSmugleaf commented
If it's ready feel free to let me handle the merge conflicts when I review it, you don't need to do them yourself, I just need to get around to it

2024-09-12 14:32 UTC, Derrek-Larson commented
> If it's ready feel free to let me handle the merge conflicts when I review it, you don't need to do them yourself, I just need to get around to it

Thanks smug, whenever you can.

2026-08-05 23:27 UTC, Vermidia commented
Going to close this as #10660 would supercede it and this hasn't been worked on in a very long time.

2026-08-05 23:27 UTC, closed without merging