Replace MK80 in squad vendors with MK80 pistol case
RMC-14/RMC-14 pull request #3182
Opened 2024-07-21 04:07 UTC by Dutch-VanDerLinde

## About the PR
add MK80 pistol case

also adds smart pistol case to smart pistol vendor for cm13 parity

## Why / Balance
cm13 parity and in todo list

## Technical details

## Media
![image](https://github.com/user-attachments/assets/df9d1eaa-f40d-4249-9aaa-6171242bc178)

![image](https://github.com/user-attachments/assets/4d1f9d17-6d54-405c-b438-8d5f566f6575)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- add: Added MK80 hand cannon pistol case

2024-07-21 06:48 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-07-21 06:48 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/specialist_loadouts.yml
> +    - id: RMCMK80Case
This one is actually supposed to be the three items individually
```suggestion
    - id: CMWeaponPistolMK80
    - id: CMMagazinePistolMK80
    - id: CMMagazinePistolMK80
```

2024-07-21 06:48 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/specialist_loadouts.yml
> +    - id: RMCMK80Case
Same with this
```suggestion
    - id: CMWeaponPistolMK80
    - id: CMMagazinePistolMK80
    - id: CMMagazinePistolMK80
```

2024-07-21 13:17 UTC, Dutch-VanDerLinde commented
requested changes done

2024-07-22 05:03 UTC, DrSmugleaf approved these changes

2024-07-22 05:03 UTC, merged