Defib requires armor to be off to use + medical Locale fixes
RMC-14/RMC-14 pull request #3211
Opened 2024-07-22 17:48 UTC by Dutch-VanDerLinde

## About the PR
some medical locale now respects pronouns
defib can only be used if armor is off

## Why / Balance
CM13 parity

## Technical details

## Media
![image](https://github.com/user-attachments/assets/a1a762bf-e91b-4f35-bbc8-1683fd0a3bce)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Defibrillating someone now requires their armor to be off.

2024-07-23 21:57 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-07-23 21:57 UTC, DrSmugleaf commented on Content.Server/Medical/DefibrillatorSystem.cs
> +            && TryComp(armor, out CMDefibrillatorBlockedComponent? comp))
This check should be done by using _inventory.GetSlotEnumerator(target, SlotFlags.OUTERCLOTHING) instead and checking if any of the items in those slots have the component

2024-07-23 21:57 UTC, DrSmugleaf commented on Content.Server/Medical/DefibrillatorSystem.cs
> +        });
We usually leave upstream files formatting unchanged for less merge conflicts
```suggestion
            {
                BlockDuplicate = true,
                BreakOnHandChange = true,
                NeedHand = true,
                BreakOnMove = !component.AllowDoAfterMovement,
                DuplicateCondition = DuplicateConditions.SameEvent,
            });
```

2024-07-23 22:43 UTC, Dutch-VanDerLinde commented
requested changes done

2024-07-25 04:47 UTC, DrSmugleaf approved these changes

2024-07-25 04:47 UTC, merged