Fix Smartgunner farsight
RMC-14/RMC-14 pull request #3253
Opened 2024-07-24 19:27 UTC by Vermidia

## About the PR

Fix smartgunner farsight zoom staying when unequipped. It also won't work or give the action outside of the eye slot now.

## Why / Balance

Discord issues, you could give a whole squad farsight with this.

## Technical details

Added equipped and unequipped events to check for if it's been removed or re-added (with farsight on). When reseting zoom, the EyeComponent is now gotten to reset max zoom to whatever zoom is defined there. Also gave the farsight component a slotflags field so it has to be in certain slots to count as equipped.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/d8463e72-ea74-450f-93bc-348f3432dc9e
(I recorded this before fixing it not working when equipped and already active)

## Breaking changes

**Changelog**

:cl:
- fix: Smartgunner combat-sight giving permanent far sight

2024-07-24 20:10 UTC, Dutch-VanDerLinde commented
does this fix runner farsight glitch too?

2024-07-24 20:15 UTC, Vermidia commented
Different components, so no I think

2024-07-25 02:17 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-07-25 02:17 UTC, DrSmugleaf commented on Content.Shared/_RMC14/FarSight/FarSightSystem.cs
> +        }
This should be its own method so that this and OnFarSightAction don't have to repeat it

2024-07-25 05:37 UTC, DrSmugleaf approved these changes

2024-07-25 05:37 UTC, merged