Fix bombard range
RMC-14/RMC-14 pull request #3321
Opened 2024-07-26 06:37 UTC by Vermidia

## About the PR

Make it so you can actually target things far away with bombard when using long-range sight (by bumping up the range to 15 like in cm-13)

## Why / Balance

Made long sight useless, fixes #3319

## Technical details

just range changes

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/e96caadd-f162-4889-a0e8-f8b2805b208b

## Breaking changes

**Changelog**

:cl:
- fix: Fix bombard range being too small to take advantage of long-range sight

2024-07-26 07:26 UTC, Kadeo64 commented
speedmerge so i can bully marines pretty please

2024-07-27 06:20 UTC, QuietlyWhisper requested changes
Shouldn't be the entire length of the screen due to the larger viewport, but this is supposed to be range 10 so that works out

2024-07-27 06:20 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Actions/Xeno/xeno_offense_actions.yml
> +    range: 14
```suggestion
    range: 10
```

2024-07-27 06:20 UTC, QuietlyWhisper approved these changes

2024-07-27 06:21 UTC, merged