Spectating Marine and Xeno huds
RMC-14/RMC-14 pull request #3340
Opened 2024-07-27 01:40 UTC by coolmankid12345

## About the PR

Observer mains rejoice! You can now see the job icons on marines that have them and the health and plasma of Xenos. Two new actions are added as a ghost where you can toggle both on and off. (Icons are placeholder as I don't have any actual ones and I'm too lazy to look, I was gonna add health icons for marines but it wasn't really working so I scrapped it) 
## Why / Balance

I love seeing the squad icons and it always feel like I am missing something when spectating so now we can see them. Xenos wasn't gonna be included but I added it too even though I don't like xenos.
## Technical details

Now this code could definitely be better but we still figuring it out again. Definitely some scuff shit in here but I hope you can take a look. 

Adds two new components called `CMGhostMarineHudComponent` and `CMGhostXenoHudComponent` which are added and removed from the two new actions. There are two `CMGhostSystems` in the server and the client to handle the removing/adding of actions and components.
## Media

https://github.com/user-attachments/assets/115da041-6f36-4002-a4ec-3048cc1e4e3e
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Marine icons and Xeno plasma/health for spectators to see

2024-07-27 06:26 UTC, Kadeo64 commented
re-fucking-joice

2024-08-08 00:59 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-08-08 00:59 UTC, DrSmugleaf commented on Content.Client/_RMC14/Marines/MarineOverlay.cs
> +                return;
These two if statements can be merged 
```suggestion
        if (!_entity.HasComponent<CMGhostMarineHudComponent>(_players.LocalEntity) &&
            !_entity.HasComponent<MarineComponent>(_players.LocalEntity))
            {
                return;
            }
```

2024-08-08 00:59 UTC, DrSmugleaf commented on Content.Server/_RMC14/Mobs/CMGhostSystem.cs
> +            SubscribeLocalEvent<GhostHearingComponent, ComponentStartup>(OnGhostStartup);
We should probably have an RMCMobObserver but for now this is fine

2024-08-13 00:51 UTC, DrSmugleaf approved these changes

2024-08-13 00:51 UTC, merged