Add defensive shield + shield logic
RMC-14/RMC-14 pull request #3365
Opened 2024-07-28 04:00 UTC by Vermidia

## About the PR

Adds the crushers defensive shield + logic for other shields when we get them.

## Why / Balance

Implementing a feature, which should make crushers a bit more viable as an evolution.

## Technical details

Adds the XenoShieldSystem and CrusherShieldSystem, the former handling basic shield logic (eating damage, breaking, adding/removing new shields) and the latter handling crusher specific parts (damping all damage types by 10, handling the action).

Shields are calculated after armor (from what I could tell on cm-13) and can have durations and decay rates.

I also ported the empower effects + the armor bars from cm-13.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/f360bde4-e3a6-419d-8b9e-ee001fa0908c

## Breaking changes

I hope not?

**Changelog**

:cl:
- add: Crushers can now use their defensive shield ability that lasts 7 seconds, which gives them a 200 hitpoint shield that takes 10 less damage from all sources, and for a short while gives them explosion immunity.

2024-07-28 13:26 UTC, KingOnBudget commented
CRUSHER SWEEP
!!!!!

2024-07-29 03:19 UTC, Dutch-VanDerLinde commented
Resolves #319

2024-07-29 16:13 UTC, Dutch-VanDerLinde commented
also resolves #259

2024-08-01 05:41 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-08-01 05:41 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Shields/RemovedShieldEvent.cs
> +[ByRefEvent]
Small style nitpick
```suggestion
﻿namespace Content.Shared._RMC14.Shields;
﻿
[ByRefEvent]
```

2024-08-01 05:41 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Shields/XenoShieldSystem.cs
> +		}
```suggestion
            Dirty(uid, shield);
        }
```

2024-08-01 05:41 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Shields/CrusherShieldSystem.cs
> +    public override void Initialize()
```suggestion
    [Dependency] private readonly XenoPlasmaSystem _xenoPlasma = default!;

    public override void Initialize()
```

2024-08-01 05:41 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Shields/CrusherShieldSystem.cs
> +        if (!TryComp<CMArmorComponent>(ent, out var armor))
```suggestion
    {
        if (!TryComp<CMArmorComponent>(ent, out var armor))
```

2024-08-01 05:42 UTC, merged