Knife Mask
RMC-14/RMC-14 pull request #3372
Opened 2024-07-28 23:08 UTC by KalimbaMachine

## About the PR
Adds sprite for when the Bayonet or throwing knife is in the mouth slot.

## Media

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![knifemouth1](https://github.com/user-attachments/assets/5cf3ed45-20a6-4b7c-9627-c8688180ecae)
![knifemouth2](https://github.com/user-attachments/assets/cee3278f-4917-45f3-9130-eb55b9b1882a)
![knifemouth3](https://github.com/user-attachments/assets/a92652e6-06ca-4825-95cc-f3d8aa6543db)

2024-07-29 03:37 UTC, QuietlyWhisper requested changes

2024-07-29 03:37 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Objects/Weapons/Melee/m5_bayonet.rsi/meta.json
You need to update the copyright source with the commit the .dmi and image are from

2024-07-29 04:09 UTC, KalimbaMachine commented on Resources/Textures/_RMC14/Objects/Weapons/Melee/m5_bayonet.rsi/meta.json
I have created the mask sprites myself.
The meta.json has been updated to reflect as such.

2024-07-30 00:54 UTC, QuietlyWhisper approved these changes

2024-07-30 00:55 UTC, merged