Scout Weapon Specialist
RMC-14/RMC-14 pull request #3390
Opened 2024-07-29 21:07 UTC by LankLTE

## About the PR

I've still got some stuff to do- opening this as a draft to motivate myself not to abandon it. ~~And get yelled at about how I've done everything wrong.~~
TODO: 
- [ ] Make the M4SPR Custom brown
- [ ] Make the invisibility friendly-fire immune
- [ ] Implement the Thermal Tarp

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-07-30 10:02 UTC, LankLTE commented
Marking this as ready for review as, I believe it's finished and ready for review. I'll be filling out the PR description shortly.

2024-08-01 05:21 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-08-01 05:21 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Stealth/RMCPassiveStealthComponent.cs
> +    public float MinOpacity = 0.2f;
On the video it seemed instant but in 13 it is supposed to slowly turn the entity invisible down to 0, at least for the stealth body bag that the scout gets. Like, actually 0. You can probably do the slowly part by storing a timespan of when this was activated and a delay for full invis, then interpolate the invis amount from that.

2024-08-01 05:21 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Stealth/RMCPassiveStealthSystem.cs
> +        invisibility.Opacity = ent.Comp.MinOpacity;
Missing a dirty call here after the data changes
```suggestion
        invisibility.Opacity = ent.Comp.MinOpacity;
        Dirty(ent.Owner, invisibility);
```

2024-08-08 00:29 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-08-08 00:29 UTC, merged