Marine helmet hides horns/antennae and species damage visual changes
RMC-14/RMC-14 pull request #3417
Opened 2024-07-30 21:35 UTC by Dutch-VanDerLinde

## About the PR
Also changes all species melee weapons to be a fist

## Why / Balance
Fists: All species now deal blunt damage, so a lizard clawing when they deal blunt doesn't make sense
Helmet change: Looks better
Damage visuals: All species bleed human blood, so them having different colored damage sprites didn't make sense

also fixes moths/arachnids/dionae/slimes not having burn visuals

## Media
![image](https://github.com/user-attachments/assets/19f8f6d0-0dce-45be-b483-29a3129337fb)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
No

2024-07-30 22:54 UTC, LankLTE commented
I think this is kind of a bummer, I like the antennae being visible

2024-07-30 23:05 UTC, Tunguso4ka commented
We had standard punch for lizards before the playtests, but i asked Smug/Whisper to leave clawing visuals.

I like them, they look nice.

It kinda brraks my mind when im punching as lizard/unathi and see standard punch visual instead of clawing one.

2024-07-30 23:48 UTC, QuietlyWhisper requested changes
I actually like the helmet not hiding head cosmetics, but on the topic of damage visuals, I originally wanted the species blood to be remade to just be a child of blood with different reagent colors, which is why it was left in the species.

2024-07-30 23:52 UTC, P-MCT commented
I'd have to agree on Tunguso on their comment.

Slash/Blunt damage is considered brute, but if you slash with machete for example, it's considered brute damage. I don't see why you wouldn't allow those with claws to keep their visuals. Like the races itself, it's a cosmetic choice that differentiates from standard.

In regards to the helmets, again this is a matter of personal opinion, I prefer the helmets hiding head related visuals, but many won't. Many liz mains for example, pride their unique design and might frown on this choice, with their horns being hidden, or hiding their glowing fin ray.

2024-07-30 23:54 UTC, Dutch-VanDerLinde commented
> I actually like the helmet not hiding head cosmetics, but on the topic of damage visuals, I originally wanted the species blood to be remade to just be a child of blood with different reagent colors, which is why it was left in the species.

Do blood pack s still work with differen t blood reagents

2024-07-30 23:59 UTC, Dutch-VanDerLinde commented
> I'd have to agree on Tunguso on their comment.
> 
> Slash/Blunt damage is considered brute, but if you slash with machete for example, it's considered brute damage. I don't see why you wouldn't allow those with claws to keep their visuals. Like the races itself, it's a cosmetic choice that differentiates from standard.
> 
> In regards to the helmets, again this is a matter of personal opinion, I prefer the helmets hiding head related visuals, but many won't. Many liz mains for example, pride their unique design and might frown on this choice, with their horns being hidden, or hiding their glowing fin ray.

Idk I just made this pr cuz i wanna punch people as a lizard

2024-07-31 00:12 UTC, Vermidia commented
I just realized Diona's here had blue blood. It should be orange because water -> sap blood happened upstream

2024-07-31 00:14 UTC, Dutch-VanDerLinde commented
> As a diona player I feel red blood visuals are gonna look really out of place. They used to be light blue, now they are light orange, but a heavy red is a stark contrast.

Agreed but its just for consistency(if i can i'll do the thing that whisper said)

2024-07-31 00:37 UTC, Rainbeon commented
As a moth player I would also really miss the antennae being visible + the insect blood, species are essentially just reskins of humans in this fork for visual flavor, and removing more of their visual flavor removes a lot of reason to play them in the first place

I like the burn visual change, however

2024-07-31 00:49 UTC, Kadeo64 commented
I wonder if it's possible to hide human hair, I think that's a bigger source of ugliness than visible horns/antennae

2024-07-31 00:50 UTC, Dutch-VanDerLinde commented
> I wonder if it's possible to hide human hair, I think that's a bigger source of ugliness than visible horns/antennae

needs something more advanced

2024-07-31 00:52 UTC, Kadeo64 commented
> needs something more advanced

did we not have a hidehair system for hardsuit helmets at some point

2024-07-31 00:53 UTC, Dutch-VanDerLinde commented
> > needs something more advanced
> 
> did we not have a hidehair system for hardsuit helmets at some point

thats hide the entire hair; for helmets, you'd want people with longhair to still appear but not clip through the helmet

2024-07-31 01:02 UTC, Dutch-VanDerLinde commented
changes:
damage visuals are back to normal, species now have their unique blood reagents (purely cosmetic, they all inject into every other species fine)

2024-08-10 05:27 UTC, QuietlyWhisper commented
below pr is preferred for helmet hiding stuff
- #3600

2024-08-10 06:02 UTC, QuietlyWhisper reviewed
Smug told me it would be better to just change only the color of the injuries and leave the blood reagents for a blood type implementation, thanks for the pr

2024-08-10 06:02 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Mobs/Species/moth.yml
> +    - HeadTop
```suggestion
```

2024-08-10 06:02 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Mobs/Species/slime.yml
> +    bloodReagent: RMCSlimeBlood
```suggestion
```

2024-08-10 06:15 UTC, QuietlyWhisper approved these changes

2024-08-10 06:16 UTC, merged