Fix gas masks to work with air tanks like the medical ones.
RMC-14/RMC-14 pull request #3528
Opened 2024-08-04 10:17 UTC by BramvanZijp

## About the PR
Gas masks now allow you to turn on internals just like the medical ones.

## Why / Balance
Because it not working a bug, plus it helps tone down the currently very oppressive boiler smokes, especially during hijack.
And if it is not a bug, somebody needs to change the fact that oxygen tanks come in the same crate as gas masks when bought in req.

## Technical details
The med gas mask uses the base ss14 gas mask as a parent, which the standard gas mask does too now, allowing you to turn on your internals if you also have an air tank.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** __this PR does not require an ingame showcase__

**Changelog**

:cl: BramvanZijp
- fix: Standard gas masks now allow for the use of internals.

2024-08-04 11:20 UTC, DrSmugleaf requested changes
How does this affect Boiler gas? Boiler gas doesn't work through inhalation of surrounding chemicals, atmos simulation isn't run for most things

2024-08-08 18:14 UTC, BramvanZijp commented
> How does this affect Boiler gas? Boiler gas doesn't work through inhalation of surrounding chemicals, atmos simulation isn't run for most things

I stand corrected on that then, but they should still work like the other ones for a few reasons, including blocking consumption, etc.

2024-08-08 18:31 UTC, deltanedas commented
can confirm that atmos devices arent ticked at all including internals, so if you have 304kpa anesthetic tank it never gets inhaled so stays at 1mpa forever

2024-08-09 02:53 UTC, Dutch-VanDerLinde commented
what do gas masks do against boiler gas in cm13

2024-08-09 02:53 UTC, Vermidia commented
Nothing :p

2024-08-09 02:55 UTC, Dutch-VanDerLinde commented
lol

2024-10-10 20:38 UTC, QuietlyWhisper commented
> can confirm that atmos devices arent ticked at all including internals, so if you have 304kpa anesthetic tank it never gets inhaled so stays at 1mpa forever

We are going to need this for surgery, but maybe we should just bypass the usage of atmos systems and make a simple new one instead.. probably a lot easier and performant than working in atmos.

2024-11-08 05:14 UTC, QuietlyWhisper commented
closing as stale

2024-11-08 05:14 UTC, closed without merging