Prevent marines from pulling parasites, localize pull whitelists
RMC-14/RMC-14 pull request #3535
Opened 2024-08-04 19:31 UTC by Dutch-VanDerLinde

fixes [discord issue](https://discord.com/channels/1168210010233376858/1269721418887725118)

https://github.com/user-attachments/assets/77d8b37c-ca10-424f-98a2-0b2a1bfc5969

2024-08-04 22:54 UTC, Dutch-VanDerLinde commented on Resources/Locale/en-US/_RMC14/pulling/pulling.ftl
> +rmc-pull-infect-self = You try to pull {$pulled}, but get jumped on and infected in the process!
```suggestion
rmc-pull-infect-self = You try to pull {$pulled}, but gets jumped on and infected in the process!
```

2024-08-04 22:54 UTC, Dutch-VanDerLinde commented on Resources/Locale/en-US/_RMC14/pulling/pulling.ftl
> +rmc-pull-infect-self = You try to pull {$pulled}, but gets jumped on and infected in the process!
```suggestion
rmc-pull-infect-self = You try to pull {$pulled}, but get jumped on and infected in the process!
```

2024-08-06 03:15 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-08-06 03:15 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Pulling/CMPullingSystem.cs
> +        _parasite.Infect(comp, user, false, true);
This should check if Infect returned true before displaying the popup

2024-08-06 03:28 UTC, Dutch-VanDerLinde commented
Reviews done

2024-08-07 23:46 UTC, DrSmugleaf approved these changes

2024-08-07 23:46 UTC, merged