Magazine box (m44 x 16)
RMC-14/RMC-14 pull request #3559
Opened 2024-08-06 07:19 UTC by FungiFellow

## About the PR

I added Speedloader Boxes for the M44's regular and Marksman Rounds
## Why / Balance

Resupplying M44 rounds is a bit more tedious than other ammo types leading to it being neglected. This will cause an uptick in the amount of M44's used
## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added M44 Speedloader Boxes
- add: Cargo Can Order M44 Reg and Marksman Rounds

2024-08-07 23:39 UTC, DrSmugleaf approved these changes
Thanks for the PR! Some of the ids need to be updated from CM to RMC but otherwise it's good

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Catalog/Fills/Crates/magazine_boxes.yml
> +    - id: CMBoxMagazineRevolverM44
```suggestion
    - id: RMCBoxMagazineRevolverM44
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Catalog/Fills/Crates/magazine_boxes.yml
> +    - id: CMBoxMagazineRevolverMarksmanM44
```suggestion
    - id: RMCBoxMagazineRevolverMarksmanM44
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_box_crafting.yml
> +  id: CMBoxMagazineRevolverM44Empty
```suggestion
  id: RMCBoxMagazineRevolverM44Empty
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_box_crafting.yml
> +  id: CMBoxMagazineRevolverM44MarksmanEmpty
```suggestion
  id: RMCBoxMagazineRevolverM44MarksmanEmpty
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_box_crafting.yml
> +  targetNode: CMBoxMagazineRevolverM44Empty
```suggestion
  graph: RMCBoxMagazine
  startNode: start
  targetNode: RMCBoxMagazineRevolverM44Empty
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_box_crafting.yml
> +  targetNode: CMBoxMagazineRevolverM44MarksmanEmpty
```suggestion
  graph: RMCBoxMagazine
  startNode: start
  targetNode: RMCBoxMagazineRevolverM44MarksmanEmpty
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_box_crafting.yml
> +    - to: CMBoxMagazineRevolverM44MarksmanEmpty
```suggestion
    - to: RMCBoxMagazineRevolverM44Empty
      steps:
      - material: RMCSheetCardboard
        amount: 1
        doAfter: 1
    - to: RMCBoxMagazineRevolverM44MarksmanEmpty
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_box_crafting.yml
> +    entity: CMBoxMagazineRevolverM44MarksmanEmpty
```suggestion
  - node: RMCBoxMagazineRevolverM44Empty
    entity: RMCBoxMagazineRevolverM44Empty
  - node: RMCBoxMagazineRevolverM44MarksmanEmpty
    entity: RMCBoxMagazineRevolverM44MarksmanEmpty
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_boxes.yml
> +  id: CMBoxMagazineRevolverMarksmanM44
```suggestion
  parent: RMCBoxMagazineBase
  id: RMCBoxMagazineRevolverM44Empty
  name: speedloader box (M44 x 16)
  description: A box for holding many speedloaders with a carrying handle.
  components:
  - type: Construction
    graph: RMCBoxMagazine
    node: RMCBoxMagazineRevolverM44Empty
  - type: Sprite
    layers:
    - state: base_m44 
    - state: magaz_reg 
      map: [ "enum.CMItemSlotsLayers.Fill" ]
    - state: text_m44 
    - state: base_type_m44_reg 
    - state: base_m44_lid 
      map: [ "lid" ]
    - state: lid_type_m44_reg 
      map: [ "lid_stripe" ]
  - type: CMItemSlots
    count: 16
    slot:
      whitelist:
        tags:
        - RMCSpeedLoaderM44

- type: entity
  parent: RMCBoxMagazineRevolverM44Empty
  id: RMCBoxMagazineRevolverM44
  suffix: Filled
  components:
  - type: CMItemSlots
    startingItem: RMCSpeedLoaderM44
    count: 16
    slot:
      whitelist:
        tags:
        - RMCSpeedLoaderM44

- type: entity
  parent: RMCBoxMagazineBase
  id: RMCBoxMagazineRevolverM44MarksmanEmpty
  name: speedloader box (Marksman M44 x 16)
  description: A box for holding many speedloaders with a carrying handle, these ones are loaded with Marksman Rounds.
  components:
  - type: Construction
    graph: RMCBoxMagazine
    node: RMCBoxMagazineRevolverM44MarksmanEmpty
  - type: Sprite
    layers:
    - state: base_m44 
    - state: magaz_reg 
      map: [ "enum.CMItemSlotsLayers.Fill" ]
    - state: text_m44 
    - state: base_type_m44_mark
    - state: base_m44_lid 
      map: [ "lid" ]
    - state: lid_type_m44_mark
      map: [ "lid_stripe" ]
  - type: CMItemSlots
    count: 16
    slot:
      whitelist:
        tags:
        - RMCSpeedLoaderM44

- type: entity
  parent: RMCBoxMagazineRevolverM44MarksmanEmpty
  id: RMCBoxMagazineRevolverMarksmanM44
```

2024-08-07 23:39 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Catalog/Fills/Crates/magazine_boxes.yml
> +  name: Speedloader box (M44 Marksman, 16x loaders)
```suggestion
  name: Speedloader box (Marksman M44, 16x loaders)
```

2024-08-07 23:55 UTC, DrSmugleaf requested changes

2024-08-07 23:55 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magazine_boxes.yml
> +  parent: RMCBoxMagazineBase
```suggestion
  parent: CMBoxMagazineBase
```

2024-08-08 00:09 UTC, FungiFellow commented
> Thanks for the PR! Some of the ids need to be updated from CM to RMC but otherwise it's good

I did think it was a bit odd that the assets had that, will update similar things on future PRs

2024-08-08 00:47 UTC, FungiFellow commented
I found the thing that keeps breaking this `id: CMBoxMagazineBase` I gotta adjust all the magazine boxes to RMC

2024-08-08 00:54 UTC, DrSmugleaf commented
> I found the thing that keeps breaking this `id: CMBoxMagazineBase` I gotta adjust all the magazine boxes to RMC

You don't need to in this PR but feel free to make a separate one for it once it's merged

2024-08-08 02:59 UTC, DrSmugleaf approved these changes

2024-08-08 02:59 UTC, merged