Adds a Scottish Trait for non-dwarves.
RMC-14/RMC-14 pull request #3561
Opened 2024-08-06 12:48 UTC by P-MCT

## About the PR

Adds a Scottish trait that's 1-1 with a dwarven accent. 

Based/Ported from a PR on https://github.com/DeltaV-Station/Delta-v/pull/608

## Why / Balance

Unlocks the accent trait to other races. (FREEEEEDOOOOOOOM!!!!!!)

Might consider expanding or making a seperate PR to allow the dwarves to be accent-less.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/073a7ea6-396c-4233-adf8-6b8593660016

**Changelog**

Added: Scottish trait/accent.

2024-08-06 14:18 UTC, Dutch-VanDerLinde requested changes
you basically recreated the entire dwarf accent just with a new name
delete all the scottish code
(ScottishAccentComponent, ScottishAccentsSystem, scottish.ftl, word_replacements.ftl)
and use the already existing ReplacementAccent component with dwarf

2024-08-06 14:18 UTC, Dutch-VanDerLinde commented on Content.Server/_RMC14/Speech/Components/ScottishAccentComponent.cs
> +{ }
```suggestion
```

2024-08-06 14:18 UTC, Dutch-VanDerLinde commented on Content.Server/_RMC14/Speech/EntitySystems/ScottishAccentsSystem.cs
> +}
```suggestion
```

2024-08-06 14:18 UTC, Dutch-VanDerLinde commented on Resources/Locale/en-US/_RMC14/accent/scottish.ftl
> +accent-scottish-words-replace-163 = snakey bastards
```suggestion
```

2024-08-06 14:18 UTC, Dutch-VanDerLinde commented on Resources/Prototypes/_RMC14/Accents/word_replacements.yml
> +    accent-scottish-words-163: accent-scottish-words-replace-163
```suggestion
```

2024-08-06 14:18 UTC, Dutch-VanDerLinde commented on Resources/Prototypes/_RMC14/Traits/cm_neutral.yml
> +    - type: ScottishAccent
```suggestion
    - type: ReplacementAccent
      accent: dwarf
```

2024-08-07 00:57 UTC, Dutch-VanDerLinde requested changes

2024-08-07 00:57 UTC, Dutch-VanDerLinde commented on Resources/Prototypes/_RMC14/Traits/cm_neutral.yml
> +  - type: trait
```suggestion
- type: trait
```

2024-08-08 00:02 UTC, DrSmugleaf approved these changes
Thanks for the PR!
There were a few leftover empty files but I deleted those now

2024-08-08 00:02 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Traits/cm_neutral.yml
> +      accent: dwarf
By convention we put sequence nodes (the dash) on the same level as the node before (components)
```suggestion
  - type: ReplacementAccent
    accent: dwarf
```

2024-08-08 00:03 UTC, merged