Sniper specialist prepare position ability
RMC-14/RMC-14 pull request #3592
Opened 2024-08-09 03:02 UTC by Dutch-VanDerLinde

draft, old pr got nuked

2024-10-07 22:30 UTC, Dutch-VanDerLinde commented
READY FOR REVIEW

2024-10-11 11:16 UTC, Dutch-VanDerLinde commented
I have no idea if this implementation is exact parity

2024-10-11 11:29 UTC, DrSmugleaf commented
I think it's correct, I'll check after tomorrow though

2024-10-31 10:04 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-10-31 10:04 UTC, DrSmugleaf commented on Content.Client/_RMC14/Armor/Ghillie/GhillieSuitSystem.cs
> +public sealed class GhillieSuitSystem : SharedGhillieSuitSystem
You don't need a separate client and server systems if they don't have any code

2024-10-31 10:04 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Armor/Ghillie/SharedGhillieSuitSystem.cs
> +            invis.Opacity = 1;
In 13 this makes you slightly more visible each shot

2024-10-31 17:46 UTC, Dutch-VanDerLinde commented
Reviews done

> Thanks for the PR!

2024-10-31 21:44 UTC, DrSmugleaf approved these changes

2024-10-31 21:45 UTC, merged

2024-11-02 13:27 UTC, mmails commented
Note that this ability should also be given to the PMC snipers and other ERT snipers with similar loadouts. Im not sure exactly how the ability is handled, just mentioning it for future reference