Tile update for Varadero
RMC-14/RMC-14 pull request #3599
Opened 2024-08-10 01:39 UTC by Aurallianz

## About the PR
Added Tiles Walls and a few objects for Varadero.

## Why / Balance
Need it for Varadero mapping.

## Media
- [x] This PR does not require an in-game showcase

**Changelog**

2024-08-13 01:09 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-08-13 01:09 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Structures/Base/base_structure.yml
> +
Small nitpick, two too many new lines at the end of the file
```suggestion
  - type: RMCDropshipBlocked

```

2024-08-13 01:09 UTC, DrSmugleaf commented on Resources/Textures/_RMC14/Structures/Doors/Airlocks/strata_door.rsi/meta.json
> +  "copyright": "Taken/modified from cmss13 at https://github.com/cmss13-devs/cmss13/blob/f7b9367cb5c083a8c052a40dece9417031e28ffe/icons/obj/structures/doors/strata/strata_doors.dmi",
This link is invalid, it leads to a 404

2024-08-15 03:00 UTC, Aurallianz commented
I will not be adding any more to this PR.

2024-08-18 04:32 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-08-18 04:32 UTC, merged