Traits YML cleanup and rearranging
RMC-14/RMC-14 pull request #3606
Opened 2024-08-10 19:28 UTC by Dutch-VanDerLinde

![image](https://github.com/user-attachments/assets/e5fa795e-43f3-46c1-a630-43759bf29b42)

2024-08-10 19:57 UTC, Rainbeon commented
There are still 2 sets of Frontal Lisp in your screenshot, one free and one which costs 2 points

2024-08-10 20:02 UTC, Dutch-VanDerLinde commented
> There are still 2 sets of Frontal Lisp in your screenshot, one free and one which costs 2 points

Fixed

2024-08-13 00:54 UTC, DrSmugleaf requested changes
Thanks for the PR!
This will remove the currently chosen traits for anyone that has them but I guess that's fine, I can try to do a database migration if I remember to

2024-08-13 00:54 UTC, DrSmugleaf commented on Resources/Locale/en-US/_RMC14/traits/traits.ftl
> +rmc-trait-scottish-accent-desc = Fer tha folk who come fae a Hielan clan.
```suggestion
rmc-trait-category-inconveniences = Inconveniences

rmc-trait-russian-accent-name = Russian accent
rmc-trait-russian-accent-desc = You come from space Russia

rmc-trait-french-accent-name = French accent
rmc-trait-french-accent-desc = You come from space France

rmc-trait-mobster-accent-name = Mobster accent
rmc-trait-mobster-accent-desc = ey gabagool fugeddaboutit I'm walkin here 

rmc-trait-spanish-accent-name = Spanish accent
rmc-trait-spanish-accent-desc = You come from space Spain

rmc-trait-scottish-accent-name = Scottish accent
rmc-trait-scottish-accent-desc = Fer tha folk who come fae a Hielan clan.

```

2024-08-16 03:43 UTC, merged