Add invulnerability time system + apply it to barricades
RMC-14/RMC-14 pull request #3684
Opened 2024-08-16 03:39 UTC by Vermidia

## About the PR

Title. It makes hits not connect if it receives a certain amount of hits in a certain time.

## Why / Balance

Make xeno deathball less deathball-y because 20 xenos attack a single barricade is...not great

## Technical details

New system! Checks AttackedEvent and GettingAttackAttemptEvent to cancel and count hits. Update loop is used to reset it.

Current values is 3 hits per 1 second. It can be adjusted and added to other things, but for now it's only on barricades and only checking if xenos attack em.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://github.com/user-attachments/assets/5fa11423-820c-4fab-b5ce-00924a6729ef

## Breaking changes

no
**Changelog**

- fix: Barricades now have a short invulnerability time if they take too many hits from xenos in a small period.

2024-08-16 08:58 UTC, DrSmugleaf requested changes

2024-08-16 08:58 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Barricade/InvulnerabilityTimeSystem.cs
> +    [Dependency] IGameTiming _timing = default!;
```suggestion
    [Dependency] private readonly EntityWhitelistSystem _whitelist = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
```

2024-08-16 08:58 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Barricade/InvulnerabilityTimeSystem.cs
> +        while (query.MoveNext(out var uid, out var timeComp))
You don't need to tick this in an update method, you can peek and dequeue on attack attempt instead, letting each attack check if the previous ones have expired their timer

2024-08-16 08:58 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Structures/Walls/barricade_metal.yml
> +    hitsToInvulnerability: 3
We should probably apply this to resin structures while we are at it as well

2024-08-16 14:25 UTC, Dutch-VanDerLinde reviewed
changelog is broken

2024-08-18 04:11 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-08-18 04:11 UTC, DrSmugleaf commented
Shoutout to the two people thumbing down this PR as if their opinion matters, when being able to do this has been a bug from day 1

2024-08-18 04:11 UTC, merged

2024-08-18 04:35 UTC, Carolyn3114 commented
WHAT DO YOU MEAN I CAN'T DELETE BARRICADES WITH MY ENTIRE XENO ARMY?