Add SEA Equipment and Gun racks
RMC-14/RMC-14 pull request #3791
Opened 2024-08-22 05:37 UTC by KalimbaMachine

## About the PR

Adds the SEA vendors with minor additions that deviate from parity: 
 *Adds Officer's Coat
 *Adds MP Security Glasses

Removed Alpha Headset from SEATech Vendor

## Media

![seaequip1](https://github.com/user-attachments/assets/a98d871a-edda-49f2-9abf-b552a8c5aeef)
![seaequip2](https://github.com/user-attachments/assets/5e7f8a48-30f0-44d0-bba4-e05e82397a9d)
![seaweapon1](https://github.com/user-attachments/assets/e5ea6e5d-48f7-4174-9352-0b96e3d6c487)

## Requirements

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added SEA Equipment and Gun Racks!

2024-08-22 08:18 UTC, QuietlyWhisper requested changes
These are the wrong types of vendors, this pr will not be merged half finished, but thank you for doing the fills.

Also please remove the officer jacket as it's not part of their uniform for the sake of recognizability.

Sec glasses can stay.

2024-08-22 09:13 UTC, KalimbaMachine commented
> These are the wrong types of vendors, this pr will not be merged half finished, but thank you for doing the fills.
> 
> Also please remove the officer jacket as it's not part of their uniform for the sake of recognizability.
> 
> Sec glasses can stay.

do you want the kind that have limited selection? or what kind should i be using here?
How can i improve it.

2024-08-22 09:38 UTC, QuietlyWhisper commented
> do you want the kind that have limited selection? or what kind should i be using here? How can i improve it.

It should be the limited selection yes, all SEA players can access these vendors and get equipment from them, they work the same as the rifleman armor vendor when done correctly.
see `Resources/Prototypes/_RMC14/Entities/Structures/Machines/Vending/Squad/rifleman.yml` for how to implement it correctly

2024-08-24 07:12 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-08-24 07:12 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Structures/Machines/Vending/Crew/senior_enlisted_advisor.yml
> +        amount: 10
This costs points, it's not a fixed amount
```suggestion
        points: 9
```

2024-08-24 07:12 UTC, merged