Add plasmamen playable species
RMC-14/RMC-14 pull request #3851
Opened 2024-08-26 23:28 UTC by Dutch-VanDerLinde

## About the PR
plasmamen are skeleton-like organisms that come from a planet a mostly plasma atmosphere
unlike other servers with plasmamen these guys do not combust when in contact with oxygen

they have a funny scream and the skeleton accent, similar to dwarves and lizards with their accent
accent can be removed with Accentless

they have a max age of 225 instead of 125, plasmamen age slower

their eye and skin color can be changed

naming scheme: (Element/Gas/Isotope/Metal/Other concepts) (Roman Numeral)

## Why / Balance
New skeleton-like species for more character customization

behaves exactly like every other species (no buffs/debuffs)

## Technical details
moves some folders around for better organization

## Media
![image](https://github.com/user-attachments/assets/f67f7d57-af66-475b-ab99-40f966ab21f9)
![image](https://github.com/user-attachments/assets/62d702bf-942f-4e34-bcdd-68dfc85fcec7)

https://github.com/user-attachments/assets/e7d320d8-adf5-4419-ab37-fa28a48a7d89

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- add: Added Plasmamen as a playable species!

2024-08-26 23:56 UTC, lanse12 commented
cartoon sound effects ahh race

2024-08-27 13:44 UTC, Kadeo64 commented
Not complaining about another species but I feel like visually they're just slimes but opaque.

2024-08-27 14:02 UTC, Dutch-VanDerLinde commented
> Not complaining about another species but I feel like visually they're just slimes but opaque. 

They r bones

2024-08-27 15:34 UTC, Tunguso4ka commented
arent plasmamen is sentient plasma in the suit?

(imho, would nice to have Starbound's Novakids)

2024-08-27 15:49 UTC, Dutch-VanDerLinde commented
> arent plasmamen is sentient plasma in the suit?
> 
> (imho, would nice to have Starbound's Novakids)

in tg station, they are skeletons that were dipped in liquid plasma being controlled by the micro-organisms inside the plasma pool

in paradise station, they are a race of skeleton-like people that live on a planet with an atmosphere high in plasma content, most of their soft tissue has fell off due to the plasma

2024-08-27 17:07 UTC, LankLTE commented
The accent might be a bit much? I mean without the suit they’re just skeletons but multicolored, the accent kind of makes that worse while being super obnoxious (imho)

2024-08-27 17:23 UTC, DangerRevolution commented
> Not complaining about another species but I feel like visually they're just slimes but opaque.

that's because Plasmamen were made before Slimes, but they were harder to port to 14 than Slimes so Slimes came here first

2024-08-27 17:24 UTC, DangerRevolution commented
> The accent might be a bit much?

Accent really needs to go IMO, RMC shouldn't make some species unfun to play alongside because it's harder to read what they say

2024-08-27 17:27 UTC, Dutch-VanDerLinde commented
> Accent really needs to go IMO, RMC shouldn't make some species unfun to play alongside because it's harder to read what they say

accent can be disabled, there are other accents that are harder to read, and the skeleton accent just adds an "ACK ACK" to the end of the sentence?? and replaces a few words

2024-08-27 18:17 UTC, troytroy400 commented
May just be me, but I feel that the emote sounds need to be made to sound less cartoony/goofy.

2024-08-27 18:37 UTC, Carolyn3114 commented
why aren't they called phoronmen?

2024-08-27 18:42 UTC, Dutch-VanDerLinde commented
> why aren't they called phoronmen?

because it sounds stupid

2024-08-27 18:42 UTC, Carolyn3114 commented
> > why aren't they called phoronmen?
> 
> because it sounds stupid

it's even stupider to have plasmamen when plasma is a xeno thing

2024-08-27 20:31 UTC, Tunguso4ka commented
> > why aren't they called phoronmen?
> 
> because it sounds stupid

but we dont have plasma as a gas in cm-ss13/RMC-14.
we have phoron. Phoron sheets, phoron glass, phoron gas tanks.

2024-08-28 02:16 UTC, QuietlyWhisper commented
It's true plasma isn't used in RMC

not reviewing this yet but you can add to `Resources/Locale/en-US/_RMC14/cm-chatsan.ftl` so the species has a xenonid translation

2024-09-06 12:00 UTC, DrSmugleaf requested changes

2024-09-06 12:05 UTC, Kadeo64 commented on Resources/Prototypes/_RMC14/Species/plasmaman.yml
> +    Undershirt: MobHumanoidAnyMarking
i wouldn't mind it being required tbh (cause lore:tm:) but that's just me

2024-09-06 12:22 UTC, Dutch-VanDerLinde commented on Resources/Prototypes/_RMC14/Voice/speech_emote_sounds.yml
> +      collection: BikeHorn
This sound exists on most other humanoid species, it's so the honk reagent makes noise

2024-09-06 12:58 UTC, Kadeo64 commented on Resources/Prototypes/_RMC14/Voice/speech_emote_sounds.yml
> +      collection: BikeHorn
no way to get honk in rmc14 without admemery and i doubt upstream will add plasmemes anytime soon

2024-09-09 20:25 UTC, Dutch-VanDerLinde commented on Resources/Prototypes/_RMC14/Datasets/Names/plasmaman_last.yml
> +﻿- type: dataset
fixed

2024-09-10 23:34 UTC, Dutch-VanDerLinde commented
New sprites
![image](https://github.com/user-attachments/assets/ed8ab858-a436-4959-8b53-274dd3ecba7f)

2024-10-08 00:33 UTC, DrSmugleaf requested changes
I have to check 13 because I remember them having a sprite that looked less skeleton-y, and Whisper doesn't like them not having a chest cavity, but I might be thinking of a different codebase

2024-10-09 14:25 UTC, Dutch-VanDerLinde commented
> I have to check 13 because I remember them having a sprite that looked less skeleton-y, and Whisper doesn't like them not having a chest cavity, but I might be thinking of a different codebase

Paradise probably

2024-11-08 04:42 UTC, QuietlyWhisper commented
closing as stale, I don't think they fit the theme and mechanics either

2024-11-08 04:42 UTC, closed without merging