Adds 4 new variations of the weed node and animations.
RMC-14/RMC-14 pull request #3938
Opened 2024-09-04 19:21 UTC by Enzymi

## About the PR
I changed the default sprite of the weed node, and added 4 variations of it which is selected at random when a weed node is constructed. 

## Why / Balance
Personally I felt they looked bad and outdated. People on discord have also stated that they want better visibility of the nodes. 

## Technical details
I changed the code in meta to modify the animation speed (a longer frame (delay 5) followed by a series of rapid ones (delay 0.1)), and increased the amount of total frames from 7 to 9. I changed xeno_weeds to make node construction pick one of 4 variations at random. 

## Media

https://github.com/user-attachments/assets/61e6acb4-3781-40fb-bed7-3158060c89c4

## Requirements

- [X ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl:
- tweak: Updates the weed node sprite with 4 new variations.

2024-09-05 02:13 UTC, GoodWheatley commented
Having variations of weed node sprites is really bad for recognizability imo

2024-09-05 08:58 UTC, Enzymi commented
> Having variations of weed node sprites is really bad for recognizability imo

I dont understand. Is it difficult to recognize a tree IRL because there are thousands of different variation of it?

2024-09-05 11:33 UTC, DangerRevolution commented
These are somehow less visible than the current nodes lol

2024-09-05 12:53 UTC, Enzymi commented
> These are somehow less visible than the current nodes lol

I disagree. The pulsating animation makes them more visible than the old ones. I can make them brighter but I am not sure what shade of dark people would like. Others have said they are good as of now because they dont stand out too much.

2024-09-05 12:55 UTC, DangerRevolution commented
> > These are somehow less visible than the current nodes lol
> 
> I disagree. The pulsating animation makes them more visible than the old ones. I can make them brighter but I am not sure what shade of dark people would like. Others have said they are good as of now because they dont stand out too much.

A lot brighter, that's for certain

2024-09-05 17:36 UTC, Rainbeon commented
> I disagree. The pulsating animation makes them more visible than the old ones. I can make them brighter but I am not sure what shade of dark people would like. Others have said they are good as of now because they dont stand out too much.

They are more visible when they are pulsating due to the movement/shift in color attracting eye, but in a resting phase they are much less visible than current and blend in with the weeds around it, from the video demonstration they seem to sit in their resting state the majority of the time as well, for ~5 seconds. This means that at your most unlucky, it may take 5 seconds for a weed node to become more readily visible than current to you upon entering a room. The resting state should probably be more noticeable in some way, perhaps by color (such as how the current ones are slightly-blue), or some other method

2024-10-10 20:28 UTC, QuietlyWhisper reviewed
I like the current ones more but maybe smug has a different opinion too

2025-02-09 02:11 UTC, DrSmugleaf requested changes
We can revisit this further down the line because I think the brightness change on the animation as a concept makes it a lot easier for people to tell both where the node is and that it is important, compared to the current one, but I think it would take too many iterations to get right at the moment while we also still have issues with resin traps not underlaying the weed texture

2025-02-09 02:11 UTC, closed without merging