You can now take over parasite eggs with a right click verb.
RMC-14/RMC-14 pull request #4013
Opened 2024-09-11 22:08 UTC by Dutch-VanDerLinde

CM13 parity

resolves #3926

https://github.com/user-attachments/assets/b657210d-ede3-46e5-9005-7e218918140c

:cl:
- add: You can now become a parasite by using a right click verb on an egg.

2024-09-12 06:05 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-09-12 06:05 UTC, DrSmugleaf commented on Content.Server/_RMC14/Xenonids/Egg/XenonidEggSystem.cs
> +        if ((int)_gameTiming.RealTime.Subtract(ghostComp.TimeOfDeath).TotalSeconds < 180)
RealTime is for UI and out of game simulation, you want CurTime
You should also be able to do this instead so you don't need to get the seconds manually and cast it to an int
```suggestion
        if (_gameTiming.RealTime.Subtract(ghostComp.TimeOfDeath) < TimeSpan.FromMinutes(3))
```

2024-09-12 06:05 UTC, DrSmugleaf commented on Content.Server/_RMC14/Xenonids/Egg/XenonidEggSystem.cs
> +public sealed class XenonidEggSystem : EntitySystem
Should probably call it XenoEggRoleSystem if you don't want to inherit the shared one and split it, just so there's not a xeno egg system and a xenonid egg system

2024-09-12 06:05 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Xenonids/Egg/XenoEggSystem.cs
> +        if (!EntityManager.TryGetComponent(uid, out GhostComponent? ghostComp))
Entity systems have a short-hand format for component methods
```suggestion
        if (!TryComp(uid, out ActorComponent? actor))
            return;

        if (!TryComp(uid, out GhostComponent? ghostComp))
```

2024-09-13 20:51 UTC, Dutch-VanDerLinde commented
Addressed review

2024-09-21 08:38 UTC, DrSmugleaf approved these changes

2024-09-21 08:38 UTC, merged