Add xeno emoting
RMC-14/RMC-14 pull request #4072
Opened 2024-09-17 23:15 UTC by Vermidia

## About the PR

All xenos can now emote! Ported the cm emotes for it too.

## Why / Balance

Parity, give xenos a tiny bit more RP potential

## Technical details

Added a server-side system just to handle the emotes, the sounds are stored on xenoComponent. Gave basexeno the emoting component, and gave xenos 5 emotes they're allowed to use.

Note I made icons for all of them, and made them colorful to match upstream's style of emotes we haven't ported yet.

Also cleaned up the felenid emote file now that punctuation for chat triggers is ignored.

## Media

https://github.com/user-attachments/assets/f36571f1-8b78-4d60-9382-5943bc9e87cc

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: All xenos minus parasites can now emote properly
- add: Xenos can now roar, growl, hiss, call for help, or swipe their tails to emote

2024-09-17 23:21 UTC, deltanedas requested changes

2024-09-17 23:21 UTC, deltanedas commented on Content.Shared/_RMC14/Xenonids/XenoComponent.cs
> +    public string? EmoteSounds = "Xeno";
use protoid

2024-09-18 00:14 UTC, Dutch-VanDerLinde commented
![image](https://github.com/user-attachments/assets/c64f890d-46a6-4871-9350-96f8d9d2879a)

can't you do something similar to this for xenos instead of making a whole new system, or is the xeno marine-to-xeno chat thing breaking it?

2024-09-18 00:16 UTC, Vermidia commented
Giving them vocal would allow them to scream and such, basically they'd get access to a ton of emotes

2024-09-21 08:39 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-09-21 08:40 UTC, merged