Make emote sounds disable-able through the settings
RMC-14/RMC-14 pull request #4138
Opened 2024-09-25 15:09 UTC by Dutch-VanDerLinde

title

:cl:
- tweak: Emote sounds for species are now properly toggled with the settings

2024-09-25 16:23 UTC, Kadeo64 commented
i love how the example video uses a felinid

2024-09-26 18:42 UTC, DrSmugleaf reviewed
Originally I wanted this to be done through a different setting since the voiceline stuff was meant for the traditional 13 voicelines being played on 14, but I don't know if people want that level of granularity or not

2024-10-04 08:31 UTC, QuietlyWhisper requested changes
I'm fine with it being implemented this way if nobody wants to spend extra effort to make separate options for this

2024-10-04 08:31 UTC, QuietlyWhisper approved these changes, later dismissed
I'm fine with it being implemented this way if nobody wants to spend extra effort to make separate options for this

2024-11-24 02:21 UTC, QuietlyWhisper commented
I'd like to look into having this merged since no alternative option has been provided since September unless @DrSmugleaf is going to make it

2024-12-06 05:18 UTC, QuietlyWhisper commented
Smug has no intentions on making this or merging this pr so Im closing it. If anyone is interested in working on this as described it will be merged.

2024-12-06 05:34 UTC, DrSmugleaf commented
The above is a complete misrepresentation of my character, anyone willing to code this is free to

2025-05-03 22:38 UTC, Dutch-VanDerLinde commented
Crashing out

2025-05-04 23:48 UTC, DrSmugleaf commented
> Crashing out

https://github.com/RMC-14/RMC-14/pull/4138#pullrequestreview-2332093028

2025-05-05 00:42 UTC, DrSmugleaf approved these changes
Done in [`fdc5455` (#4138)](https://github.com/RMC-14/RMC-14/pull/4138/commits/fdc5455e0488cf5da6a6cff74577c375a6e44202)

2025-05-05 00:42 UTC, merged