Mk221 Tactical Shotgun
RMC-14/RMC-14 pull request #4193
Opened 2024-09-29 15:15 UTC by Cyberanarchbee

## About the PR

Added the MK221 Tactical shotgun to the roster of weapons. It has not been mapped or added to appropriate vendors, merely the item now exists.

## Why / Balance

Mostly for parities sake, CM13 has one, but it would help fill the armouries aboard the Almayer.

## Technical details

Mostly just added the RSI pulled from CM13 and changed the pump shotguns code to be more appropriate to the MK221. Otherwise, should be fairly simple. 

## Media

<img width="94" alt="Screenshot 2024-09-29 155321" src="https://github.com/user-attachments/assets/8d4a35c7-2627-4bb0-983d-6300d8e1b7fd">

The mk221 with various attachments and its brand new stock!

## Requirements

- [TICK] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [TICK] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Added the MK221 tactical shotgun and its appropriate stock!

🆑 
- add: Mk221 Tactical Shotgun
- add: Mk221 Tactical Shotgun Stock

2024-09-29 15:25 UTC, Cyberanarchbee commented
changes i need to make here: turns out the mk221 is not a useable name, would take suggestions to fit the rest of the themeing,

someone said the stock sits a little low?

2024-10-08 05:25 UTC, KittenColony commented
M58A3 for a name

stock shouldn't be an issue but maybe move it up slightly?

2024-10-08 22:25 UTC, DrSmugleaf commented
> changes i need to make here: turns out the mk221 is not a useable name, would take suggestions to fit the rest of the themeing,
> 
> someone said the stock sits a little low?

We have it noted down as M890, so replace any usages of MK221 with M890

2024-10-09 00:41 UTC, Cyberanarchbee reviewed
M890!!!!

2024-10-09 00:43 UTC, Cyberanarchbee commented
shit i changed the name in the code, but github is refusing to allow me to change the rsi name. working on it.

2024-10-09 01:02 UTC, Cyberanarchbee commented
RSI check supposedly failed, same with YAML, looks fine on my end.

2024-11-15 05:10 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-11-15 05:10 UTC, DrSmugleaf commented on Resources/Textures/_RMC14/Objects/Weapons/Guns/Shotguns/m890.rsi/meta.json
> +  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/7cb618c69b75873f3ce893022fe08d1233b3152d/icons/obj/items/weapons/guns/guns_by_map/desert/guns_obj.dmi",
The in-hands are not from this dmi alone
```suggestion
  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/7cb618c69b75873f3ce893022fe08d1233b3152d/icons/obj/items/weapons/guns/guns_by_map/desert/guns_obj.dmi, https://github.com/cmss13-devs/cmss13/blob/106c92cdf232ebc12c9d7a2feb23956c6755496f/icons/mob/humans/onmob/items_lefthand_1.dmi, https://github.com/cmss13-devs/cmss13/blob/4047c473d4d2f3e58e68efdec5aa95d0676bf4d1/icons/mob/humans/onmob/items_righthand_1.dmi",
```

2024-11-15 08:06 UTC, merged

2024-11-18 08:38 UTC, Rainbeon commented
This has blown up the YAML linter and RSI validator