Add Parasite Observer Strain
RMC-14/RMC-14 pull request #4210
Opened 2024-10-01 17:28 UTC by JustSome1Nearby

## About the PR
Added New Xeno Strain - Parasite Observer

## Why / Balance
Contributes to making more playable strains with the update!

## Technical details
This one wasnt hard, i just took major components of parasite and made them into Parasite Base, from wich Normal (Has Hiding) and Observer (No hiding, but runner's Zoom) paras separated. The Parasite has its own neat Strain description too, just like the Warden prae.

(TO NOTE - For some reason everything works OK, but the RMC-ADMIN-ACTION UI summons... Parasite Base? Instead of Parasite... Like i DID change ID to the correct one... every other way of summoining Parasites: like Eggs, Carriers, Ghost role take-overs from both of em - works FINE and WILL BE FINE in game, but this iz just a thing. Doesnt affect gameplay, so i hope its OK, and can be fixed later when working with that UI)

## Requirements
- [x ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Parasite Observer Strain!

2024-10-02 01:38 UTC, deltanedas requested changes

2024-10-02 01:38 UTC, deltanedas commented on Resources/Prototypes/_RMC14/Entities/Mobs/Xeno/parasite.yml
> +  suffix: Base
base prototypes should be abstract not suffixed

2024-10-02 01:38 UTC, deltanedas commented on Resources/Prototypes/_RMC14/Entities/Mobs/Xeno/parasite.yml
> +  id: CMXenoParasiteBase # TODO RMC14 slowly die off weeds
remove the todo its been done ages ago

2024-10-02 01:38 UTC, deltanedas commented on Resources/Locale/en-US/_RMC14/xeno/xeno-strains.ftl
> +  You loose:
lose

2024-10-02 01:38 UTC, deltanedas commented on Resources/Prototypes/_RMC14/Entities/Mobs/Xeno/parasite.yml
> +
gleep

2025-01-30 10:51 UTC, AverageNotDoingAnythingEnjoyer commented
Sad day for Para mains

2025-01-30 10:57 UTC, JustSome1Nearby commented
Think i tried to PR this right long ago, but moved to a place with no access to my PC, and after that ... Just didnt play much, i dunno, was tired i guess

Maybe i should do this properly

2025-01-31 00:59 UTC, QuietlyWhisper commented
I think this is still recoverable, I'll mark it as a draft so one of us can pick it up another time

2025-02-04 14:32 UTC, JustSome1Nearby commented
I made a fixed PR, since the previous repository had other parasite sprites and stuff... think its easier just to just do a clean new one (maybe its worse to do like that, dunno)

2025-02-04 14:32 UTC, closed without merging