add more underwear variants
RMC-14/RMC-14 pull request #4221
Opened 2024-10-02 20:43 UTC by Dutch-VanDerLinde

CM13 parity

![image](https://github.com/user-attachments/assets/c77539be-5bf0-4e03-88fd-14752a8482b3)
![image](https://github.com/user-attachments/assets/9dcebb8f-1453-4f46-86ec-1f115f620c98)

## Breaking changes

:cl:
- add: Added snow, jungle, desert and black variants of underwear

2024-10-02 20:45 UTC, troytroy400 commented
Does this include the black long sleeve by chance?

2024-10-02 20:49 UTC, troytroy400 commented
> > Does this include the black long sleeve by chance?
> 
> YES

My fucking hero.

2024-10-04 08:25 UTC, QuietlyWhisper requested changes
Remove the tanga please, we decided against porting it

2024-10-04 11:18 UTC, Dutch-VanDerLinde commented
> Remove the tanga please, we decided against porting it

it's removed but why

2024-10-09 18:13 UTC, GiggIess commented
Why is the tanga not being ported?

2025-01-24 03:02 UTC, Dutch-VanDerLinde commented
any chance this could get a re-review

2025-02-08 12:41 UTC, Dutch-VanDerLinde commented
closing because CM got new underwear sprites

2025-02-09 01:06 UTC, Dutch-VanDerLinde commented
added new 
![image](https://github.com/user-attachments/assets/7df5836f-cfa0-4622-8927-aaf1fc9c1e63)
![image](https://github.com/user-attachments/assets/be7782bb-5f9d-478e-827e-89495a9a9b14)
![image](https://github.com/user-attachments/assets/dd725dfd-ccc1-4316-a8c5-09139d1b13cb)


underwear sprites from the latest CM13 build

2025-02-09 01:07 UTC, Dutch-VanDerLinde commented
and fixed some conflicts

2025-03-12 09:41 UTC, DrSmugleaf requested changes
GitHub kind of mangled the diff but you can bring back the ones that were removed that were in the game

2025-03-12 15:04 UTC, Dutch-VanDerLinde commented
> GitHub kind of mangled the diff but you can bring back the ones that were removed that were in the game

Added back the removed ones

2025-03-15 07:33 UTC, DrSmugleaf approved these changes

2025-03-15 07:33 UTC, merged