add xeno announcement for when drone tax ends
RMC-14/RMC-14 pull request #4294
Opened 2024-10-06 00:46 UTC by deltanedas

## About the PR
`It has been long enough, we will no longer accumulate evolution points.`

## Why / Balance
- saves someone having to either set a timer or wait patiently until evo stars going backwards to tell everyone tax is over
- if you arent aware of it, it might seem like a bug that you are *losing* evo. now it will be much more obvious

this isnt a cm13 thing so **no parity here**, just good tax fun

## Technical details
naughty system bool to track announcement being made

## Media
![01:45:51](https://github.com/user-attachments/assets/ffd23289-fc93-4f43-ba08-f62f84822c5a)

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Xenos now get an announcement when they stop accumulating evo points past the maximum (15 minutes in).

2024-10-06 01:45 UTC, DrSmugleaf requested changes
This is the same time as the T3 unlock announcement which is what people use in 13 to time it, could still have it but it might be a bit much in the chat, or be loud sound-wise if both play at the same time

2024-10-06 03:22 UTC, deltanedas commented
can make it silent or just be a popup then to avoid sound spam

2024-10-08 00:18 UTC, deltanedas commented
actual sound is null by default already

2024-10-08 00:34 UTC, DrSmugleaf commented
> actually sound is null by default already @DrSmugleaf do you want it to just be a popup

That would make both popups clip right?

2025-01-26 05:28 UTC, DrSmugleaf commented
Reopen if you come back to this

2025-01-26 05:28 UTC, closed without merging

2025-01-26 07:32 UTC, deltanedas commented
t3 popups have existed for a while so