let xenos melee rogue xenos + let xenos break weeds
RMC-14/RMC-14 pull request #4298
Opened 2024-10-06 01:21 UTC by deltanedas

## About the PR
xenos can now fight eachother if they are not in the same hive

xenos can also break weeds, even their own

## Why / Balance
- there was a todo
- they already can with abilities so

for weeds, right now any drone can build a wall/membrane on the weed node to kill weeds, so now it is just easier. theres a similar pr for unnesting marines

## Technical details
if the target has XenoFriendly now it also checks if they are in the same hive
so you can bonk rogue xenos and for xeno v xeno you can break the other hives weeds and whatever else

because setting hive member for **every weed entity** would probably be too taxing, weeds no are longer XenoFriendly (without setting the hive member they would be treated as a rogue xeno's weeds)

nest entity still has XenoFriendly since there are far less nests than weeds, so setting hive member in this case is acceptable

## Media
figure out which xeno is rogue 99% impossible
![02:09:42](https://github.com/user-attachments/assets/58ad1608-d5de-45fe-baf1-9ef7dd05eaa3)

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- tweak: Xenos can now break their own weeds.

2024-10-07 02:45 UTC, DrSmugleaf requested changes
Xeno's aren't supposed to be able to hit their own weeds. If this is for nesting, that's fixed by letting them unnest in a different PR
I wouldn't really worry about performance for that, the xeno weeds component itself is heavier

2024-10-07 03:58 UTC, deltanedas commented
ok ill give hive member to weeds and keep it as XenoFriendly

2024-10-07 05:52 UTC, DrSmugleaf commented
This also will need to account for round-start weeds

2024-10-07 07:07 UTC, deltanedas commented
would it be fine to just assign the distress call hive to every xenofriendly entity after the planet is loaded

2024-10-08 00:34 UTC, DrSmugleaf commented
> would it be fine to just assign the distress call hive to every xenofriendly entity after the planet is loaded

Sure

2024-10-08 01:48 UTC, deltanedas commented
seems to work as expected on shivas at least

2024-10-08 22:09 UTC, DrSmugleaf approved these changes

2024-10-08 22:10 UTC, merged