Porting and debranded CM containers. Only sprites added.
RMC-14/RMC-14 pull request #4327
Opened 2024-10-07 07:53 UTC by troytroy400

## About the PR
Porting sprites for containers.

## Why / Balance
Containers.

## Technical details
Just sprites.

## Media
N/A

## Requirements
N/A

Check the boxes below to confirm that you have in fact seen these (put an X in the brackets, like [X]):
-->
- [ X ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
N/A

2024-10-07 12:28 UTC, Kadeo64 commented
RIP lockmart logo

2024-10-10 20:24 UTC, QuietlyWhisper requested changes

2024-10-11 01:11 UTC, DrSmugleaf submitted a review, later dismissed

2024-10-11 01:12 UTC, DrSmugleaf commented on Resources/Textures/_RMC14/Structures/containers.rsi/meta.json
> +  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/a69663ee8d9e3a980d486a1ee05efa44f79abc17/icons/obj/structures/props/contain.dmi",
```suggestion
  "copyright": "Taken from cmss13 at https://github.com/cmss13-devs/cmss13/blob/a69663ee8d9e3a980d486a1ee05efa44f79abc17/icons/obj/structures/props/contain.dmi, modified by troytroy40 on GitHub",
```

2024-10-11 01:13 UTC, merged