Add storage drawing toggle to some storages
RMC-14/RMC-14 pull request #4536
Opened 2024-10-19 23:48 UTC by Dutch-VanDerLinde

QOL feature from CM-ss13 which allows you to take the first item out of storage by clicking

:cl:
- add: You can now toggle storage like pouches and armor to eject the first item when you click on it. This toggle can be accessed with a verb.

2024-10-23 23:04 UTC, DrSmugleaf requested changes
That toggle in 13 switches between take out first and take out last, not unequipping and taking out item I thought, or does it depend by storage?

2024-10-24 11:31 UTC, Dutch-VanDerLinde commented
> That toggle in 13 switches between take out first and take out last, not unequipping and taking out item I thought, or does it depend by storage?

Our click interaction is different than 13's so unless you want to make inventory slots be unequipable unless you drag drop it to your hand it has to be that

2024-10-24 11:31 UTC, Dutch-VanDerLinde commented
Like clicking a bag in 13 opens the storage, here it unequips the item

2024-10-29 08:09 UTC, DrSmugleaf commented
> Our click interaction is different than 13's so unless you want to make inventory slots be unequipable unless you drag drop it to your hand it has to be that

Might be good as an option yeah, reagent canister pouches do this already but I'd have to think on it

2024-10-29 13:43 UTC, Dutch-VanDerLinde commented
> > Our click interaction is different than 13's so unless you want to make inventory slots be unequipable unless you drag drop it to your hand it has to be that
> 
> 
> 
> Might be good as an option yeah, reagent canister pouches do this already but I'd have to think on it

Reagent canisters click to take out the auto injector, this PR makes the same component the auto injector uses toggleable, that's it

2025-02-09 03:16 UTC, Dutch-VanDerLinde commented
@DrSmugleaf 

Revised most of the PR,

https://github.com/user-attachments/assets/cfc38e9c-f94f-4777-8f7e-7c57ed2b4e9f


now you can toggle between taking the last item, unequiping the storage, or opening the storage on click

2025-02-09 03:18 UTC, Dutch-VanDerLinde commented
Revised most of the PR,



https://github.com/user-attachments/assets/cbe1454d-211d-4fc2-8f34-5a5ca9e8abd0



now you can toggle between taking the last item, unequiping the storage, or opening the storage on click

2025-05-03 11:25 UTC, DrSmugleaf requested changes
Thanks for the PR!
Sorry it took me so long to review this again, I see what you mean now
Would it be possible to have it toggle between last > first > unequip > open, by adding the first step?
That should cover everything even with our different keybinds
Another thing for another time is making Shift+E and Shift+B respect the draw order if set to first

2025-05-03 16:42 UTC, Dutch-VanDerLinde commented
> Thanks for the PR! Sorry it took me so long to review this again, I see what you mean now Would it be possible to have it toggle between last > first > unequip > open, by adding the first step? That should cover everything even with our different keybinds Another thing for another time is making Shift+E and Shift+B respect the draw order if set to first


https://github.com/user-attachments/assets/775f6564-f33f-41e8-ba32-f760b457842d

Done

2025-05-03 21:28 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2025-05-03 21:29 UTC, merged