add corpsman gloves to the vendor
RMC-14/RMC-14 pull request #4597
Opened 2024-10-25 22:16 UTC by Dutch-VanDerLinde

## About the PR

## Why / Balance

## Technical details

## Media

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-10-26 00:19 UTC, QuietlyWhisper requested changes

2024-10-26 00:19 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Structures/Machines/Vending/bundles.yml
> -    - CMHandsBlackMarine
bundle description is wrong after this change

2024-10-26 02:07 UTC, Dutch-VanDerLinde commented
fixed

2024-10-31 21:47 UTC, DrSmugleaf approved these changes

2024-10-31 21:47 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Structures/Machines/Vending/Squad/medic.yml
>        - id: CMMRE
Small nitpick but in 13 the gloves are above the MRE
```suggestion
      - id: CMVendorBundleSquadMedicalApparel
      - id: RMCHandsLatexMarine
        name: combat sterile gloves
      - id: CMMRE
```

2024-10-31 21:47 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Structures/Machines/Vending/Squad/medic.yml
> +        name: combat sterile gloves
```suggestion
```

2024-10-31 21:47 UTC, merged