Update dropship crew equipment rack and restricted firearms options
RMC-14/RMC-14 pull request #4611
Opened 2024-10-27 16:47 UTC by mnemosynium

## About the PR
Dropship crew equipment rack:
* Added M44 revolver
* Removed MK80 pistol
* Added MK80 pistol case to Restricted Firearms
* Added SU6 pistol case to Restricted Firearms
* Replaced M44 speed loader ammo with M44 speed loader marksman ammo

## Why / Balance
Consistency with other equipment vendors.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Added M44 revolver to the dropship crew equipment rack
- tweak: Added SU6 case to the dropship crew equipment rack
- tweak: Replaced MK80 with MK80 case in the dropship crew equipment rack
- fix: Replaced M44 ammunition with M44 speed loader ammunition in the dropship crew equipment rack

2024-10-29 15:55 UTC, Dutch-VanDerLinde commented
THIS. IS. NOT. PARITY.

2024-10-29 18:44 UTC, mnemosynium commented
Feel free to close it as not-parity, but you're perfectly capable of communicating that like an adult.

2024-10-30 00:22 UTC, QuietlyWhisper commented
Its an inside joke with the community, not intended to be taken offensively,

but anyway, we'll check this out later and see what is parity again, and if this is not, consider if its worth changing.

I havent checked yet but the changes are a bit strange, could you elaborate which vendors youre trying to match them with?

2024-10-30 01:15 UTC, mnemosynium commented
For the MK80, I’m checking the medic, engineer, and SL vendors, which offer it only in a case, not standalone. The Command vendor is the only one with the MK80 sold individually, and unlike the dropship crew vendor, it also stocks MK80 magazines.

I added the SU6 under Restricted Firearms to align with the setup in other vendors, though I wasn’t fully certain about it.

For M44 ammo, the equipment vendor sells it for 10 points, right next to a weapon vendor offering it for free. The dropship crew vendor is the only vendor that charges for standard M44 ammo.

2024-10-31 15:09 UTC, mnemosynium commented
I've changed this PR to only replace the standard M44 speedloader with MK80 magazines, maintaining near-parity.

2024-10-31 21:42 UTC, DrSmugleaf requested changes
This is meant to be in the weapons rack, not the equipment one, this one should keep its m44 ammo.
CMMagazinePistolVP78 should be the one getting replaced with CMMagazinePistolMK80 as thats our equivalent

2024-11-01 05:14 UTC, DrSmugleaf approved these changes

2024-11-01 05:14 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Structures/Machines/Vending/Crew/auxiliary.yml
> +         amount: 14
From 13 these are 16, though the other two commented ones are also incorrect, but we can fix that later
```suggestion
         amount: 16
```

2024-11-01 05:14 UTC, merged