Add set pose
RMC-14/RMC-14 pull request #4682
Opened 2024-11-03 02:32 UTC by Dutch-VanDerLinde

## About the PR
CM13 parity, add the set pose action

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

:cl:
- add: Added setting your character's pose. This  can be updated in-round with an action, useful for giving your character time-specific flavor text.

2024-11-04 03:48 UTC, troytroy400 commented
Holy shit this is unbelievably peak. Biggest marine buff since CAS.

2024-11-04 12:35 UTC, Kadeo64 commented
This is John Marine. He is... [hitting the griddy]

2024-11-04 18:31 UTC, deltanedas commented
This is John Marine. He is a xenonid.

2024-11-08 04:40 UTC, QuietlyWhisper requested changes
I'd rather have this as a right click verb instead of a action bar thing, there's going to be too much going on up there as we continue development.

2024-11-08 12:09 UTC, Dutch-VanDerLinde commented
Man we really gotta port the little side panel with buttons from CM

2024-11-08 12:26 UTC, mmails commented
> Man we really gotta port the little side panel with buttons from CM

Good luck forcing everyone to play on separated :pain:

2024-11-08 12:27 UTC, Dutch-VanDerLinde commented
Separated is superior.

2024-11-08 17:58 UTC, Dutch-VanDerLinde commented
> I'd rather have this as a right click verb instead of a action bar thing, there's going to be too much going on up there as we continue development.

made it a verb instead 
![image](https://github.com/user-attachments/assets/a54b3bc8-9364-479f-af8f-a83deb1c7ef1)

2024-11-25 01:07 UTC, QuietlyWhisper approved these changes
Seems fine now needs code review

2025-03-15 19:36 UTC, mmails commented
Bump, is this pr dead in the water? This would be a nice addition

2025-03-29 08:50 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2025-03-29 08:50 UTC, merged