Add armor preferences
RMC-14/RMC-14 pull request #4735
Opened 2024-11-06 18:38 UTC by Dutch-VanDerLinde

## About the PR
adds selecting armor variant

## Why / Balance
CM13

resolves #2260
resolves #2261
resolves #2262
resolves #2263
resolves #2264
resolves #2265

## Technical details

## Media

https://github.com/user-attachments/assets/5c160823-d374-463c-b7aa-28a5fbab8f02

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

:cl:
- add: Added armor variants. You can select which armor variant you get with in the vendor in the character customization screen. The variants are just cosmetic changes.

2024-11-07 00:30 UTC, Kadeo64 commented
that light ridged armor looks clean

2024-11-07 13:26 UTC, Dutch-VanDerLinde commented
Only problem is the save button doesn't enable if you change armor variants in the character editor

2024-11-08 07:26 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-11-08 07:45 UTC, DrSmugleaf approved these changes

2024-11-08 07:46 UTC, merged