knocking
RMC-14/RMC-14 pull request #4878
Opened 2024-11-19 22:46 UTC by DummeHytteOst

## About the PR
Added knocking to windows

## Why / Balance
#4864
## Media

https://github.com/user-attachments/assets/985db4a9-36d5-43d5-9ec2-52e87b5495f7

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

2024-11-19 22:48 UTC, Dutch-VanDerLinde commented
do resolves #4864 in the description so it auto closes

2024-11-19 22:56 UTC, DummeHytteOst commented
> do resolves #4864 in the description so it auto closes

neat, didn't know you could do that, thanks 👍

2024-11-22 00:17 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-11-22 00:17 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Structures/Windows/windows.yml
> +  - type: InteractionPopup
Cooldown for this is supposed to be 10 seconds to avoid spam

https://github.com/user-attachments/assets/b7912a60-47bc-4989-8bb3-7a928bd816be

2024-11-22 02:37 UTC, Dutch-VanDerLinde requested changes

2024-11-22 02:37 UTC, Dutch-VanDerLinde commented on Resources/Prototypes/_RMC14/Entities/Structures/Windows/windows.yml
> +        variation: 0.125
```suggestion
  - type: InteractionPopup
    interactDelay: 10 
    interactSuccessString: comp-window-knock
    messagePerceivedByOthers: comp-window-knock
    interactSuccessSound:
      path: /Audio/Effects/glass_knock.ogg
      params:
        variation: 0.125
```

2024-11-25 01:08 UTC, QuietlyWhisper approved these changes

2024-11-27 01:28 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2024-11-27 01:28 UTC, merged