Add Hive structures
RMC-14/RMC-14 pull request #4978
Opened 2024-11-29 04:16 UTC by blueDev2

## About the PR

CM13 parity
## Why / Balance

## Technical details

## Media

## Requirements

- [ ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-30 14:52 UTC, Skarletto commented
collectors, evopods and the pool are not parity, they were removed long ago from cm13 
![image](https://github.com/user-attachments/assets/e3057ec4-24fa-4e71-b3a9-ba0333b3c413)
![image](https://github.com/user-attachments/assets/09d85ac4-7cac-450f-858f-c34dbba709d0)

The wiki is a lie and contains wrong information

2024-12-03 03:03 UTC, blueDev2 commented
> collectors, evopods and the pool are not parity, they were removed long ago from cm13

I know, I was just porting pngs over and those were in there

2025-01-26 06:14 UTC, DrSmugleaf requested changes
Thanks for the PR!

2025-01-26 06:14 UTC, DrSmugleaf commented on Content.Server/_RMC14/Xenonids/Construction/EggMorpher/EggMorpherSystem.cs
> +namespace Content.Server._RMC14.Xenonids.Construction.EggMorpher;
All of this code can and should be in shared, so you don't need a separate system
If you need to change behavior on the client you can do net is client or is server checks

2025-01-26 06:14 UTC, DrSmugleaf commented on Content.Client/_RMC14/Xenonids/Construction/EggMorpher/EggMorpherSystem.cs
> +}
This can be moved to shared

2025-01-26 06:14 UTC, DrSmugleaf commented on Content.Server/_RMC14/Xenonids/Weeds/XenoWeedsSystem.cs
> +        QueueDel(ent);
This can be moved to shared with server checks for the entity deletions

2025-01-26 06:14 UTC, DrSmugleaf commented on Content.Shared/_RMC14/Xenonids/Construction/HivePylonSystem.cs
> +}
System is empty you can delete this

2025-02-28 19:58 UTC, 0tito commented
Alright, i hereby declare this pr has passed all reviews, merge this now smug

2025-02-28 19:59 UTC, pumpkin-pwr commented
oh man i sure hope this doesnt get stuck in review limbo :clueless

2025-03-01 11:26 UTC, DrSmugleaf requested changes
Need a changelog written out for this on the PR description

2025-03-02 01:55 UTC, DrSmugleaf requested changes
Comms tower pylon is only supposed to give OB protection when gestating the King

2025-03-02 05:56 UTC, DrSmugleaf approved these changes
Thanks for the PR!

2025-03-02 05:57 UTC, merged