Add visual effect during treatment
RMC-14/RMC-14 pull request #5007
Opened 2024-12-01 03:08 UTC by MetalSage

## About the PR

Adds a visual effect to the treatment (Defibrillator, blood transfusion, surgery, treatment kits or surgical line, CPR).
Close #4953

## Why / Balance

CM13 parity

## Technical details

Adds to the DoAfter system the ability to apply an effect at runtime.

## Media

https://github.com/user-attachments/assets/f4650b80-1ea2-4e26-bf5f-0f25b8ff6b7d

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Added visual effects when you heal Marines

2024-12-07 00:10 UTC, DrSmugleaf requested changes
Thanks for the PR!

2024-12-07 00:10 UTC, DrSmugleaf commented on Content.Shared/DoAfter/SharedDoAfterSystem.Update.cs
> +                        SpawnAttachedTo(doAfter.Args.TargetEffect, targetXform.Coordinates);
This needs an INetManager.IsServer check so it doesn't spam spawn clientside entities

2024-12-07 22:21 UTC, MetalSage commented
If needed I can also add a field to enter the time between effects.

After deleting a duplicate effect:

https://github.com/user-attachments/assets/ea3e6297-6801-46c9-ba7a-ba63ea26d6e6

2024-12-13 17:10 UTC, DrSmugleaf approved these changes

2024-12-13 17:10 UTC, merged