USS Savannah: Episode IV An Old Hope
RMC-14/RMC-14 pull request #5097
Opened 2024-12-09 20:04 UTC by Tunguso4ka

## About the PR

### Feel free to ping me here or in discord and ask/demand for some additions.

A fourth refit of USS LCS-14 Savannah:
- Requi line is now a little bit bigger.
- Third refit of engineering
- Escape pods TODO
- Escape shuttles TODO
- Power TODO
- More cozy places to slowly bleed out 

## Media

![image](https://github.com/user-attachments/assets/ece0aaf6-ae38-47e1-a915-5573f2ed0245)
![image](https://github.com/user-attachments/assets/51bf7c13-a933-47b0-97c5-db1e18c3f25c)

**Changelog**

:cl:
- add: A somewhat unlucky USS Savannah returns from her refit.

2024-12-11 17:24 UTC, Tunguso4ka commented
I think i overdid amount of escape pods (12) and lifeboats (2).

2024-12-15 21:31 UTC, UnicornOnLSD commented
sick stuff

Besides if the amount of pods proves to be an issue it can always be modified later. On one side it's a smaller ship but on the other there's still a lotta personnel so ya know

2025-01-19 05:54 UTC, fidso commented
USS -> UNS

2025-01-26 07:15 UTC, DrSmugleaf requested changes
Thanks for the PR!

Holding the east might be too easy because of how close the prep vendors are, not sure yet with the pop difference, might not matter

2025-01-26 07:15 UTC, DrSmugleaf commented on Resources/Prototypes/Maps/Pools/default.yml
> +  - Savannah
I'm not sure on reenabling it yet but I don't want to leave this PR in limbo, I know some downstreams really want to use it too and it would be a really nice map to have here for PvE or HvH

2025-01-26 09:24 UTC, Tunguso4ka commented on Resources/Prototypes/Maps/Pools/default.yml
> +  - Savannah
So, remove it?

2025-02-07 02:26 UTC, DrSmugleaf commented on Resources/Prototypes/Maps/Pools/default.yml
> +  - Savannah
For now yeah

2025-02-07 10:10 UTC, Tunguso4ka commented on Resources/Prototypes/Maps/Pools/default.yml
> +  - Savannah
Done.

2025-02-07 11:49 UTC, DrSmugleaf approved these changes

2025-02-07 11:50 UTC, DrSmugleaf approved these changes
we are so back

2025-02-07 11:50 UTC, merged