CO's Desert Eagle - PR MADE AT THE REQUEST OF IceStormTheDragon
RMC-14/RMC-14 pull request #5116
Opened 2024-12-12 19:22 UTC by Boaz1111

## About the PR

Added the Commanding Officer's Vintage Desert Eagle, included with its ammo HI and HIAP, and moving the Mateba's belt location to the CO's vender with the Deagle's belt temporary until loadouts come out.

Sprites listed made by [RyanStrudfelt](https://github.com/RyanStrudfelt)
Resources/Textures/_RMC14/Objects/Weapons/Guns/Ammunition/Magazines/deagle.rsi/50AERegular.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Ammunition/Magazines/deagle.rsi/mag-1.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/base.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/bolt-open.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/icon.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/inhand-left.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/inhand-right.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/mag-0.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/wielded-inhand-left.png
Resources/Textures/_RMC14/Objects/Weapons/Guns/Pistols/deaglecustom.rsi/wielded-inhand-right.png

## Why / Balance

CM13 had the CO's Desert Eagle, so im porting it here.

## Technical details

Majority of the coding is in the CO's Deagle itself, the rest is just making sure the Deagle is able to be accessed by the CO, as stated above.

Media
## Media

Earlier test of the Deagle and its attachments, but this is what it will generally be like minus the textures made by Ryan
![image](https://github.com/user-attachments/assets/41fb65fa-9b2c-4b74-b8f2-d0b5e000e9e7)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

none
**Changelog**

:cl: IceStormTheDragon, RyanStrudfelt
- add: CO's Deagle
- add: Desert Eagle Belt
- add: Mateba and Desert Eagle belt added to the CO weapon vendor
- add: .50 AE HI and HIAP magazines
- remove: Round start Mateba belt for the CO (Got to get it from the vendor)

2024-12-12 19:49 UTC, Nairodian commented
I'm not a legal expert or anywhere close to knowledgeable to how it applies to games, especially one like this; but isn't Desert Eagle a trademarked name? Not sure if that'd cause problems or of concern.

2024-12-12 19:51 UTC, Boaz1111 commented
test fails seem unrelated

2024-12-12 19:51 UTC, Boaz1111 commented
> I'm not a legal expert or anywhere close to knowledgeable to how it applies to games, especially one like this; but isn't Desert Eagle a trademarked name? Not sure if that'd cause problems or is of concern.

CM13 also uses it, but I'm not sure if we're allowed to use it

2024-12-12 20:16 UTC, IceStormtheDragon commented
> I'm not a legal expert or anywhere close to knowledgeable to how it applies to games, especially one like this; but isn't Desert Eagle a trademarked name? Not sure if that'd cause problems or is of concern.

Just checked and turns out, yes it is, so ill be working out a new name with Ryan for it just to be safe.

2024-12-12 20:22 UTC, noctyrnal commented
> > I'm not a legal expert or anywhere close to knowledgeable to how it applies to games, especially one like this; but isn't Desert Eagle a trademarked name? Not sure if that'd cause problems or is of concern.
> 
> Just checked and turns out, yes it is, so ill be working out a new name with Ryan for it just to be safe.

If you're taking suggestions, 'Hand Cannon' is a commonly used alternative iirc.

2024-12-12 20:28 UTC, Boaz1111 commented
It is, but it feels a bit bland tbh

2024-12-12 20:29 UTC, IceStormtheDragon commented
Im getting things sorted with the PLs to see if Desert Eagle is fine to use, if not we will be calling it the "Magnum Automatic", suggested by Ryan.

2024-12-12 20:34 UTC, MACMAN2003 commented
i suggest an alternative name if desert eagle is not allowed: Desert Falcon
(it also fits in with the name of the in game company, the falling falcons)

2024-12-12 20:35 UTC, IceStormtheDragon commented
My suggestion was the "Winter Falcon" but, sounds kinda cheap considering context so we will probably go with what Ryan made up.

2024-12-12 23:25 UTC, IceStormtheDragon commented
Magnum Automatic was decided upon by myself and asking the other CO's so, thats what we will be going with,

2024-12-12 23:33 UTC, Boaz1111 commented
wtf, something went wrong

2025-01-26 09:14 UTC, QuietlyWhisper requested changes

2025-01-26 09:14 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Pistols/co_magnumautomatic.yml
New content IDs should be RMC not CM

2025-02-05 15:29 UTC, AverageNotDoingAnythingEnjoyer commented
So is that a yes on using Deseart Eagle name?
<img width="907" alt="Screenshot 2025-02-05 at 18 28 39" src="https://github.com/user-attachments/assets/c67967cd-7bf9-4612-a395-d36902c7c75e" />

2025-02-09 04:04 UTC, IceStormtheDragon commented
We decided on "D50 Winter Wyvern" as the name of it after some discussion in VC.

2025-02-13 01:11 UTC, QuietlyWhisper commented
Pr now also removes the mateba belt from the CO belt slot on spawn and moves it to the vendor, you have to pick up one or the other now

2025-02-13 01:11 UTC, QuietlyWhisper commented
review issues are still not resolved though

2025-02-13 14:44 UTC, Boaz1111 commented
Apologies, have been, and am still busy with stuff, haven't had time for this, dunno when I will

2025-03-02 06:38 UTC, DrSmugleaf commented
Replaced by https://github.com/RMC-14/RMC-14/pull/5771 ty for the work on it

2025-03-02 06:38 UTC, closed without merging