Add Rodentia
RMC-14/RMC-14 pull request #5174
Opened 2024-12-18 04:41 UTC by paige404

## About the PR

Adds the Rodentia, a species of rat/mouse/squirrel/bat/hamster/rabbit/beaver/possum-like humanoids. As seen on [DeltaV](https://github.com/DeltaV-Station/Delta-v/pull/1511), [Goob](https://github.com/Goob-Station/Goob-Station/pull/610), [Costmatic Drift](https://github.com/cosmatic-drift-14/cosmatic-drift/pull/404), and others.

Credit goes to @portfiend for initially developing the Rodentia for DeltaV.

## Why / Balance

We got dogs, cats. Why not rats? Many marines have been eager for this PR.

Balance: Rodentia on other servers are quite small. I'd initially wanted to split the difference and make these dwarf-proportioned, and I still don't think that would be an issue. As far as I can tell, we don't have a dwarf-meta powergamer problem; the full tile sprite width does a lot to keep dwarves in check. For now, as requested by Whisper in the discord, rodentia are human size.

It's weird though. Please consider dwarfing the rats.

## Technical details

C#: Adds a new Last First naming scheme which Rodentia use elsewhere.
YAML: Adds rodentia, their associated sprites/markings, speech sounds, name conventions, etc.
PNG/JSON: Adds rodentia sprites, as well as custom mask sprites that fit the Rodentia Round Snout.

Note: the Bat Snout is too large and clips out of the rodentia gas mask by 1 pixel. This is because of #5173, which I may have a solution in the wings for. Expanding the gas mask even further looks awkward on default rodentia faces, I believe the best course of action will be to

## Media

![2024-12-16 22_29_33-Rouny's Marine Corps 14](https://github.com/user-attachments/assets/3fe16598-2fd3-4524-97ea-99af717db152)
![2024-12-17 21_35_28-Rouny's Marine Corps 14](https://github.com/user-attachments/assets/0ba56eda-d92e-410c-8139-c5a29858ef70)
(The above screens show the dwarf-proportioned rodentia, which have since been made full size. They demonstrate a variety of outfits and equipment)

![2024-12-17 22_38_18-Rouny's Marine Corps 14](https://github.com/user-attachments/assets/56261f0e-c3a6-4e1c-b8a7-5484c260bd7b)
(This screen shows a squirrel the size of a human man)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-18 05:13 UTC, QuietlyWhisper requested changes
You have a bunch of sprites with no source linking to the tg body parts.

You'll need to find the source of these original sprites and link them, and double check the license used.

2024-12-18 05:13 UTC, QuietlyWhisper commented on Content.Shared/Humanoid/NamingSystem.cs
> +                        ("last", GetLastName(speciesProto)), ("first", GetFirstName(speciesProto, gender)));
This should have a comment on it since it's an upstream file, so it won't be overwritten by an update

Something like "this is for [species]"

2024-12-18 05:13 UTC, QuietlyWhisper commented on Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
> +    LastFirst,
This should have a comment on it since it's an upstream file, so it won't be overwritten by an update

Something like "this is for [species]"

2024-12-18 05:13 UTC, QuietlyWhisper commented on Resources/Audio/_RMC14/Voice/Rodentia/mouse_squeak.ogg
This is a duplicate file of the mouse squeak used in mice mobs, you could probably reuse that one to save space.

2024-12-18 05:13 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Mobs/Rodentia/cheek_markings.rsi/meta.json
> +  "copyright": "https://github.com/tgstation/tgstation/blob/8024397cc81c5f47f74cf4279e35728487d0a1a7/icons/mob/human_parts_greyscale.dmi, modified by DrSmugleaf and portfiend",
Source is incorrect

2024-12-18 05:13 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Mobs/Rodentia/body_markings.rsi/meta.json
> +  "copyright": "https://github.com/tgstation/tgstation/blob/8024397cc81c5f47f74cf4279e35728487d0a1a7/icons/mob/human_parts_greyscale.dmi, modified by DrSmugleaf and portfiend",
Source is incorrect.

2024-12-18 05:13 UTC, QuietlyWhisper commented on Resources/Audio/_RMC14/Voice/Rodentia/attributions.yml
This is a duplicate file of the mouse squeak used in mice mobs, you could probably reuse that one to save space.

2024-12-18 05:13 UTC, QuietlyWhisper commented on Resources/Textures/_RMC14/Mobs/Rodentia/head_markings.rsi/meta.json
> +  "copyright": "https://github.com/tgstation/tgstation/blob/8024397cc81c5f47f74cf4279e35728487d0a1a7/icons/mob/human_parts_greyscale.dmi, modified by DrSmugleaf and portfiend",
Source is incorrect.

2024-12-18 05:20 UTC, paige404 commented on Resources/Audio/_RMC14/Voice/Rodentia/attributions.yml
I could! I figured moving it might help if rodentia speech/emote sounds get updates. Which, I'd love to see those expanded both here and elsewhere in the future. I can reuse the animal mouse squeak for now if that's preferred though.

2024-12-18 05:23 UTC, paige404 commented
> You have a bunch of sprites with no source linking to the tg body parts.
> 
> You'll need to find the source of these original sprites and link them, and double check the license used.

That was the attribution on portfiend's sprites on DeltaV. I'll update these to be like the Vulpkanin's sprite attributions.

2024-12-18 23:44 UTC, paige404 commented
I have done my best to address all feedback. I noticed that while Delta-V's sprite metadata claims CC-BY-SA-3.0, their own code (and thus our usage of their sprites) is under AGPLv3. So I corrected the metadata for the imported sprites. Hopefully I've done it right this time?

2024-12-19 07:02 UTC, QuietlyWhisper commented
> I have done my best to address all feedback. I noticed that while Delta-V's sprite metadata claims CC-BY-SA-3.0, their own code (and thus our usage of their sprites) is under AGPLv3.

The sprites used for vulp are from a commit before deltav was AGPLv3, they're also not ported directly from deltav but from another server that already handled the problem, which you'll essentially need to do here as well, unless they were added during/after AGPLv3, in which case we can't accept these sprites / whatever was sourced from deltav under any circumstances due to the license conflict. Sorry that you had put so much effort into this, but it's very unlikely we'll be able to add these for reasons out of control of either of us.

2024-12-19 07:20 UTC, paige404 commented
> > I have done my best to address all feedback. I noticed that while Delta-V's sprite metadata claims CC-BY-SA-3.0, their own code (and thus our usage of their sprites) is under AGPLv3.
> 
> The sprites used for vulp are from a commit before deltav was AGPLv3, they're also not ported directly from deltav but from another server that already handled the problem, which you'll essentially need to do here as well, unless they were added during/after AGPLv3, in which case we can't accept these sprites / whatever was sourced from deltav under any circumstances due to the license conflict.

The vulp attribution lines specifically [do say](https://github.com/RMC-14/RMC-14/pull/4699/files#diff-42da705d201c8454e5eff0fe2133bfb9a25b30449f993269f3014eff16b00915R4) that they are ported from Delta-V.

Rodentia were added after the code went AGPL. _However_, DeltaV's listed license for these sprites is CC BY SA 3.0 as you can see on their own meta.json files (e.g. [this one](https://github.com/DeltaV-Station/Delta-v/blob/f49142ca8d7ceac483094444c372e849309dc02b/Resources/Textures/DeltaV/Mobs/Customization/Rodentia/body_markings.rsi/meta.json)). Additionally, the creator of the PR gave consent for ports in [the PR itself](https://github.com/DeltaV-Station/Delta-v/pull/1511).

2024-12-19 07:25 UTC, deltanedas commented
AGPL is for code, assets like sprites (and *especially* ones that are -SA) are still the same license

2024-12-19 07:25 UTC, QuietlyWhisper commented
> The vulp attribution lines specifically [do say](https://github.com/RMC-14/RMC-14/pull/4699/files#diff-42da705d201c8454e5eff0fe2133bfb9a25b30449f993269f3014eff16b00915R4) that they are ported from Delta-V.

Yes, because it was explicitly copied from the fork that provided it, the sprites come from deltav, not the fork, obviously.

2024-12-19 07:34 UTC, QuietlyWhisper commented
> Additionally, the creator of the PR gave consent for ports in [the PR itself](https://github.com/DeltaV-Station/Delta-v/pull/1511#issuecomment-2339581002).

Thanks for sharing this supporting information, it should be enough to be perfectly fine with this, I'll run it by smug as well and ask a few others just in case.

It's probably safe to assume the creator doesn't really understand how licensing works but it should be fine to port now.

![image](https://github.com/user-attachments/assets/4e77f87b-1a88-456f-a2ed-1d406dc0e9dd)

2024-12-19 07:39 UTC, QuietlyWhisper approved these changes
You could probably add more xenonid translations for "rodent" and "rodents" if you care, but otherwise, assuming everything here has been tested to work and render correctly, this seems good to go. I'd still like smug to do their own review regardless as usual.

Additionally, you're absolutely invited to make a wiki addition to the species page, as the person advocating for this species.
https://wiki.rouny-ss14.com/wiki/Species

2024-12-19 07:45 UTC, paige404 commented
> You could probably add more xenonid translations for "rodent" and "rodents" if you care, but otherwise, assuming everything here has been tested to work and render correctly, this seems good to go. I'd still like smug to do their own review regardless as usual.
> 
> Additionally, you're absolutely invited to make a wiki addition to the species page, as the person advocating for this species. https://wiki.rouny-ss14.com/wiki/Species

At this point, I would rather do that chatsan expansion as a tiny follow-up PR. Probably after I've finished working on next PR, which is to fix issue #5173.

I'll gladly add Rodentia to the wiki though!

2024-12-19 08:30 UTC, paige404 commented
Oh! And regarding testing: I've been pretty thorough. I tested every armor I could find, most of the CM outfits available through the Debug > Set Outfit command, tested all the markings, tested gas mask, coif, rebreather, and sterile mask (it seems like the medical gas mask isn't really used? if that changes I'm happy to work out a sprite for that too). Tested xeno interactions like parasite latching, devouring, wall nesting, chestbursting. Tested carrying, dragging, wielding weapons. I can't guarantee there aren't any edge cases I missed, but I've been as thorough as possible.

I didn't update all my PR screenshots for the full-sized rats, but I've continued to test quite a lot since sizing them up.

2024-12-20 20:39 UTC, paige404 commented
> Additionally, you're absolutely invited to make a wiki addition to the species page, as the person advocating for this species. https://wiki.rouny-ss14.com/wiki/Species

How's this? https://wiki.rouny-ss14.com/wiki/Species

2024-12-22 11:33 UTC, DrSmugleaf approved these changes

2024-12-22 11:33 UTC, DrSmugleaf commented
Thanks for the PR!
Shotout to the people reacting to this and other species PRs with a thumbs down as if we give a fuck when reviewing or merging PRs!

2024-12-22 11:33 UTC, merged

2024-12-22 13:23 UTC, deltanedas commented
nooooooo you cant port species time to out myself with a react