Adds press armor light
RMC-14/RMC-14 pull request #5253
Opened 2024-12-27 15:59 UTC by DummeHytteOst

## About the PR
gave the press armor a light

## Why / Balance
resolves #4331

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

- [x] By submitting this code and/or assets, I confirm that I either own them or have provided the correct necessary licenses to use and distribute them. I agree to be fully responsible for any legal claims or issues arising from the use of these materials.

**Changelog**
:cl:
- add: Press armor now has a light.

2025-01-06 17:34 UTC, Dutch-VanDerLinde commented on Resources/Prototypes/_RMC14/Entities/Clothing/OuterClothing/marine_armor.yml
> +  parent: RMCBaseMarineArmorLight
make this inherit from light armor and remove the duplicate components
the armor has the exact same stats as light armor
this is so there's less copypaste

2025-01-07 11:13 UTC, DummeHytteOst commented on Resources/Prototypes/_RMC14/Entities/Clothing/OuterClothing/marine_armor.yml
> +  parent: RMCBaseMarineArmorLight
Done, had to make ItemCamouFlage variation blank, otherwise it ended up looking like the M3 medium armor, with whatever camou was active

2025-01-07 12:10 UTC, DrSmugleaf requested changes
Thanks for the PR!

2025-01-07 12:10 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Clothing/OuterClothing/marine_armor.yml
> +    camouflageVariations:
For empty blocks this is more explicit and clear
```suggestion
    camouflageVariations: { }
```

2025-01-07 14:29 UTC, DummeHytteOst commented on Resources/Prototypes/_RMC14/Entities/Clothing/OuterClothing/marine_armor.yml
> +    camouflageVariations:
gotcha, should be ready now

2025-01-11 08:30 UTC, DrSmugleaf approved these changes

2025-01-11 08:30 UTC, merged