boom
RMC-14/RMC-14 pull request #5263
Opened 2024-12-29 08:26 UTC by AverageNotDoingAnythingEnjoyer

## About the PR

Removed starting headset from CMO, Doctor, Nurse and Maint Tech
Resolves #5259 

## Why / Balance

It's parity, specifialy can be found in https://github.com/cmss13-devs/cmss13/blob/6e6c781ab074b64a57e41fabad884ebdab0b2a91/code/modules/gear_presets/uscm_medical.dm and https://github.com/cmss13-devs/cmss13/blob/6e6c781ab074b64a57e41fabad884ebdab0b2a91/code/modules/gear_presets/uscm_ship.dm

## Technical details

4 line YAML change

## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

- [X] By submitting this code and/or assets, I confirm that I either own them or have provided the correct necessary licenses to use and distribute them. I agree to be fully responsible for any legal claims or issues arising from the use of these materials.

**Changelog**

:cl: J C Denton
- remove: Removed starting headsets from CMO, Doctor, Nurse and Maintenance Technician.

2025-01-07 10:19 UTC, DrSmugleaf requested changes
The colony bit was left out since the liaison would be able to talk with survivors on the colony as they can buy a colony key, and I need to check the details on how thats supposed to work in 13 still, but the rest is fine for now unless you want to look into it

2025-01-07 13:49 UTC, AverageNotDoingAnythingEnjoyer commented
> The colony bit was left out since the liaison would be able to talk with survivors on the colony if comms are repaired as they can buy a colony key, and I need to check the details on how thats supposed to work in 13 still, but the rest is fine for now unless you want to look into it

I'm not sure myself but here's this in 13-q-a
<img width="1080" alt="Screenshot 2025-01-07 at 16 48 51" src="https://github.com/user-attachments/assets/50e37035-e270-4602-a730-26ce244dc425" />

2025-01-07 13:58 UTC, Dutch-VanDerLinde commented
Survivors can't even repair comms rn because they don't have engineering skill

2025-01-11 08:43 UTC, DrSmugleaf approved these changes

2025-01-11 08:43 UTC, merged