mac-15
RMC-14/RMC-14 pull request #5264
Opened 2024-12-29 17:13 UTC by Binbagg

## About the PR
mac-15 port
## Why / Balance
parity
## Technical details
yml
## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).

- [X] By submitting this code and/or assets, I confirm that I either own them or have provided the correct necessary licenses to use and distribute them. I agree to be fully responsible for any legal claims or issues arising from the use of these materials.

**Changelog**

2024-12-29 17:29 UTC, QuietlyWhisper commented
I'm so happy we're going to have three different 9mm ammo that are all incompatible with each other and do different damage. It's almost like whoever designed the weapons originally made a damage modifier on the guns for a reason. 

Can't wait to clean this shit up after parity this is a disaster.

2024-12-29 17:35 UTC, Binbagg commented on Resources/Audio/_RMC14/Weapons/Guns/Gunshots/gun_mac15.ogg
yeah mb about that and magazine stuff, knew it was fucked just wanted to get it working ingame so i made some up some bullshit ID's, will fix later

2025-01-17 07:24 UTC, texas1234567889 commented
![image](https://github.com/user-attachments/assets/c1dc6216-8f65-4af3-a9c0-0510e334baf1)
![image](https://github.com/user-attachments/assets/e7f33d37-43ac-4a56-81dc-f795997238f2)
    FixedPoint2 AccuracyAddMult, // Affects the accuracy of all shots fired by the weapon. Conversion from 13: accuracy_mod or accuracy_unwielded_mod
    FixedPoint2 DamageFalloffAddMult, // This affects the damage falloff of all shots fired by the weapon. Conversion to RMC: damage_falloff_mod
    double BurstScatterAddMult, // This affects scatter during burst and full-auto fire. Conversion to RMC: burst_scatter_mod
    int ShotsPerBurstFlat, // Modifies the maximum number of shots in a burst.
    FixedPoint2 DamageAddMult, // Additive multiplier to damage.
    float RecoilFlat, // How much the camera shakes when you shoot.
    double ScatterFlat, // Scatter in degrees. This is how far bullets go from where you aim. Conversion to RMC: CM_SCATTER * 2
    float FireDelayFlat, // The delay between each shot. Conversion to RMC: CM_FIRE_DELAY / 10
    float ProjectileSpeedFlat // How fast the projectiles move. Conversion to RMC: CM_PROJECTILE_SPEED * 10

2025-01-20 10:07 UTC, texas1234567889 commented
![image](https://github.com/user-attachments/assets/f0a602de-62b7-4efe-bcfb-8296b324b5c6)
acutal mac15 stats (i had forgotten to take the reflex sight off)

2025-01-26 07:17 UTC, DrSmugleaf requested changes
Stats need to be updated to be correct, texas posted them from my stream
Correct mac-15 ones are in texas' second comment

2025-01-26 09:13 UTC, QuietlyWhisper requested changes
New content IDs should be RMC not CM

2025-01-26 09:13 UTC, QuietlyWhisper commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Rifles/mar40_rifle.yml
> +  description: A cheap, reliable assault rifle chambered in 7.62x39mm. Commonly found in the hands of criminals or mercenaries, or in the hands of the UPP or CLF.
```suggestion
  description: A cheap, reliable assault rifle chambered in 7.62x39mm. Commonly found in the hands of criminals or mercenaries, or in the hands of the SPP or CLF.
```

2025-02-09 10:28 UTC, Binbagg commented
should be ready

2025-02-19 05:50 UTC, DrSmugleaf requested changes
Thanks for the PR!

2025-02-19 05:50 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Rifles/mar40_rifle.yml
> +  name: MAR-40 Assault Rifle
```suggestion
  name: MAR-40 battle rifle
```

2025-02-19 05:50 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Rifles/mar40_rifle.yml
> +          - RMCAttachmentBarrelCharger
This isn't supposed to allow a barrel charger
```suggestion
```

2025-02-19 05:50 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/Rifles/mar40_rifle.yml
> +          - RMCAttachmentBarrelCharger
Much less spawn with one randomly you absolute weapon
```suggestion
```

2025-02-19 05:50 UTC, DrSmugleaf commented on Resources/Prototypes/_RMC14/Entities/Objects/Weapons/Guns/SMGs/mac15.yml
> +  name: MAC-15 submachine gun
```suggestion
  name: MAC-15 submachinegun
```

2025-02-19 07:16 UTC, Binbagg commented
🙏

2025-02-21 08:39 UTC, DrSmugleaf approved these changes

2025-02-21 08:40 UTC, merged